### ISSUE TITLE
누리고 버그요, 옵션 등록이 안됩니다.

### ISSUE THREAD

**Issue by edu21mentor** [bjrambo/nurigo#106]
![default](https://cloud.githubusercontent.com/assets/23256090/19999453/d1728f6e-a2b5-11e6-8946-de799f1cad13.jpg)

상품 옵션 선택시 등록버튼이 없어요 ㅜㅜ

**Comment by bjrambo** [comment]
720p 화면에서 정상적으로 최대한 나타날 수 잇도록 수정하도록 하겠습니다.

**Comment by bjrambo** [comment]
fixed in 89f6ce5
