### ISSUE TITLE
상품등록시 구매시그룹추가 기능이 안되네요.

### ISSUE THREAD

**Issue by mingukang** [bjrambo/nurigo#112]
상품등록시에 옵션정보에서

구매시그룹추가 기능을 사용하려고 하는데요.

기본 준회원에서 정회원 등업 설정을 해두고

구매를 아무리 많이 해도 자동등업 처리가 안되네요;;;

**Comment by bjrambo** [comment]
Fixed in 7e48bec

결제관리에서 결제를 완료할 경우 그룹추가가 될 수 있도록 하였습니다.

혹시 다른 문제 없는지 테스트해보시고 피드백 남겨주시면 다시 확인해보도록 할께요~~!!

**Comment by mingukang** [comment]
수정 조치 해주셔서 감사합니다. 수고 많으세요.
테스트 해보았는데 일반상품 주문경우 준회원에서 정회원 이동이 되나
준회원,정회원 모두 체크가 되네요. 준회원에서 정회원으로 자동 그룹 변경되서
준회원은 체크가 빠지고 정회원만 되야 하는데 둘다 체크가 됩니다.

그리고 일반 상품은 그룹 변경이 되는데
콘텐츠상품을 판매하면 그룹 변경이 안되네요.
