### ISSUE TITLE
KG이니시스 신규 IDC 이전에 따른 IP 추가 공지

### ISSUE THREAD

**Issue by andjfrrk** [bjrambo/nurigo#114]
이니시스 모바일과 웹표준 모듈의 업데이트가 필요합니다.
아래는 관련 이메일 내용입니다.
(텍스트로 오지 않고, 이미지로 첨부되어 왔네요.)

![kg_inicis1](https://cloud.githubusercontent.com/assets/10268222/20856566/2b160c0c-b955-11e6-9a8b-bfd7d02391f3.png)
![kg_inicis2](https://cloud.githubusercontent.com/assets/10268222/20856568/320b6098-b955-11e6-94da-7ea0b68fe291.png)

**Comment by bjrambo** [comment]
문제는 없어 보이네요 :) 감사합니닷.
