### ISSUE TITLE
상품구매시 그룹변경 테스트 해보았습니다.

### ISSUE THREAD

**Issue by mingukang** [bjrambo/nurigo#115]
상품구매시 그룹변경 옵션 테스트 해보았습니다.
일단 수정 조치 해주셔서 감사합니다. 수고 많으세요.

테스트 해보았는데 일반상품 주문경우 준회원에서 정회원 이동이 되나
준회원,정회원 모두 체크가 되네요. 준회원에서 정회원으로 자동 그룹 변경되서
준회원은 체크가 빠지고 정회원만 되야 하는데 둘다 체크가 됩니다.

그리고 일반 상품은 그룹 변경이 되는데
콘텐츠상품을 판매하면 그룹 변경이 안되네요.

**Comment by bjrambo** [comment]
기존그룹을 삭제하는 방법은 리스크가 클것으로 생각되어서 판단하기로는 그냥 제외하는걸로 생각했었어요.

자체적으로 해당 그룹이 어떤 그룹을 어디서 사용하는지 모르는 경우가 있기 때문에 그룹을 추가하여 권한을 부여하는 방법이 훨신 다방면 사이트에서 사용하기에 편하기 때문이에요..

상품 구매완료시 콘텐츠항목에서도 그룹이 변화할 수 있는 구간도 따로 있는 구간에 코드를 안만들었군요. 해당 부분도 추가해보도록 하겠습니다..

**Comment by bjrambo** [comment]
fix in 268cba4bf33ce7793347f60dde3a0ab3fbf9c747
