### ISSUE TITLE
옵션가격을 만약에 11111원을 했을경우 최종결제시 결제실패가 떠버립니다.

### ISSUE THREAD

**Issue by garnecia** [bjrambo/nurigo#116]
이니시스 스탠다드 페이 사용중인데,

결제금액 끝자리가 0원이 아니고, 1원이런식으로 되면 결제취소가 되어버리네요

혹시가 해서 남겨봅니다.

**Comment by bjrambo** [comment]
정상적으로 요청이 되었음에도 불구하고 결제취소로 처리가 된다면 이니시스측에 문의해보시는것이 어떨까요?
