### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by coda2000** [bjrambo/nurigo#117]
첨부한이미지 처럼 제품상세보기에서 여러줄입력칸을 만들수는 없나요
![q01](https://cloud.githubusercontent.com/assets/24768508/21473470/0f0e1c7c-cb50-11e6-9b33-93eadee540b4.gif)

**Comment by bjrambo** [comment]
죄송하지만 저희 누리고 모듈이 아닌것 같네요.

해당 사이트 URL이 없어서 검색으로 대략 알아보니 타 CMS을 이용한 것 같아요. 해당 CMS와 쇼핑몰 관리센터에 문의해보시길 바랍니다.
