### ISSUE TITLE
상품관리 모듈 > 상품분류 관리에서 삭제가 안됩니다.

### ISSUE THREAD

**Issue by aproworld** [bjrambo/nurigo#118]
상품 분류 등록후 등록된 분류 삭제시 "분류명 값은 필수입니다" 메세지 출력이 되며, 삭제가 안됩니다.

또한 분류 항목 드래그해서 이동시 아래와 같이 자바스크립트 오류가 있습니다.
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
jquery.min.js?20161010055950:5 POST http://도메인/ 500 (Internal Server Error)

######### XE 기본 정보
Your version: 1.8.27
app : nginx/1.10.2
xe_version : 1.8.27
php : 5.6.29
db_type : mysqli
use_rewrite : Y
use_db_session : N
use_ssl : none
phpext : core, ereg, libxml, openssl, zlib, cgi-fcgi, imagick, apcu, bz2, calendar, curl, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, ldap, exif, mcrypt, mysql, mysqli, pdo_mysql, pdo_sqlite, phar, shmop, simplexml, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, xml, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, mhash, apc, zend opcache
module : adminlogging(1.7), advanced_mailer(1.8.1), apro(0.1), board(1.7.2), cashpay(1.0), currency(1.0), cympusadmin(1.4), cympuser(1.0), epay(2.2), epos(1.0), inipaymobile(1.0), inipaystandard(0.1.1), kcp(1.1), krzip(1.8.0), marketplace(1.4), ncart(1.7), nmileage(1.5.4), nproduct(1.7), nstore(2.2), nstore_digital(1.9), nstore_digital_contents(1.1), paynoty(1.1), paypal(1.0), seo(1.8.19), store_review(0.2), store_search(0.9), supercache(1.3.3), syndication(5.0.0), textmessage(3.2)
addon : adminlogging(1.7), captcha_member(1.7), noduplicate(1.0), oembed(1.0), trolley(0.3)
layout : mangofruit2(0.1), mangofruit3(0.1), topTheme(0.1), xe_official(1.7), xedition(1.9), user_layout(1.7)
widget : apro(0.1), aproworld(0.1), aproworld_oS(0.1), category_menu(1.2), counter_status(1.7), frontdisplay(1.0)
widgetstyle : flashTitle(0.1), simple(1.7)

**Comment by bjrambo** [comment]
fixed in 039feeb
