### ISSUE TITLE
이니시스 웹표중방식 결재 마지막에 오류!문제입니다.

### ISSUE THREAD

**Issue by smg2512** [bjrambo/nurigo#119]
https://www.xpressengine.com/index.php?mid=qna&document_srl=23201917
해결좀 해주시겠어요?ㅠㅠ

**Comment by bjrambo** [comment]
https://github.com/conory/rhymix/commit/a519db608dfa8d5b1f6825206836820e64de20ec 참고.

**Comment by smg2512** [comment]
도움이 되실까봐요! 위에 부분 2달넘게 만에 해결되었습니다.
먼저... 참고하라고 하신 부분은 거의다 누리고 마스터 파일에서 수정이 되었더라구요.
xe에 쉬운설치에 이니시스 웹표준삭제 후 재 설치 하니깐 해결되었습니다!
