### ISSUE TITLE
PAYPAL 결제스킨 오류, 수정이 안되나봐요?

### ISSUE THREAD

**Issue by LIMJK** [bjrambo/nurigo#120]
최근에 올려지는 문제점은 패치판에 추가되는데,
요건 적용이 안되네요... T T

**Comment by bjrambo** [comment]
순차적으로 급한건 먼저 개선하고, 그다음 순위가밀릴 수 잇습니다..

해당 부분은 HTML부분의 스킨상의 문제이기 때문에 스킨단위에서 직접 수정하셔서 잠시 임시방편으로 쓰셔도 괜찮습니다..
