### ISSUE TITLE
상품 등록 시 아래와 같은 에러가 표시 됩니다.

### ISSUE THREAD

**Issue by Dragonhaptic** [bjrambo/nurigo#121]
상품 등록 시 아래와 같은 오류가 표시 됩니다. 

Prepared statement failed: INSERT INTO `xe_nproduct_extra_vars` (`item_srl`, `name`) VALUES (?, ?)Field 'value' doesn't have a default value Array ( [0] => mysqli_stmt Object ( [affected_rows] => -1 [insert_id] => 0 [num_rows] => 0 [param_count] => 2 [field_count] => 0 [errno] => 1364 [error] => Field 'value' doesn't have a default value [error_list] => Array ( [0] => Array ( [errno] => 1364 [sqlstate] => HY000 [error] => Field 'value' doesn't have a default value ) ) [sqlstate] => HY000 [id] => 22 ) [1] => is [2] => 172 [3] => item_delivery_free )

**Comment by bjrambo** [comment]
안녕하세요
저희 개발환경에서 정확한 원인을 알기위한 문제 재연이 되고 있지 않습니다.

혹시 어떻게 설정하셨는지,

자세한 서버의 환경등의 정보가 있으면 좀 더 고치는데 도움이 될 것 같습니다!

**Comment by Dragonhaptic** [comment]
메일 qw5414@naver.com 으로 서버 관련 정보 보냈습니다.

**Comment by flowerrain** [comment]
안녕하세. 람보님. 누리고 쇼핑몰에서 같은 현상이 나타나서 글 남깁니다.


상품등록을 하거나, 등록된 상품을 수정하면 저 역시 아래와 같은 에러가 발생합니다.

Prepared statement failed: INSERT INTO `xe_nproduct_extra_vars` (`item_srl`, `name`) VALUES (?, ?)Field 'value' doesn't have a default value Array ( [0] => mysqli_stmt Object ( [affected_rows] => -1 [insert_id] => 0 [num_rows] => 0 [param_count] => 2 [field_count] => 0 [errno] => 1364 [error] => Field 'value' doesn't have a default value [error_list] => Array ( [0] => Array ( [errno] => 1364 [sqlstate] => HY000 [error] => Field 'value' doesn't have a default value ) ) [sqlstate] => HY000 [id] => 52 ) [1] => is [2] => 5746 [3] => item_delivery_free )


또한, 장바구니(cart) 에서 페이지 생성후 cart 페이지 관리 - 결제폼관리에서 '새 그룹추가'를
클릭해도 비슷한 에러가 발생합니다.

Prepared statement failed: INSERT INTO `xe_ncart_orderform_fieldsets` (`fieldset_srl`, `module_srl`, `fieldset_title`, `regdate`) VALUES (?, ?, ?, ?)Field 'fieldset_name' doesn't have a default value Array ( [0] => mysqli_stmt Object ( [affected_rows] => -1 [insert_id] => 4348322 [num_rows] => 0 [param_count] => 4 [field_count] => 0 [errno] => 1364 [error] => Field 'fieldset_name' doesn't have a default value [error_list] => Array ( [0] => Array ( [errno] => 1364 [sqlstate] => HY000 [error] => Field 'fieldset_name' doesn't have a default value ) ) [sqlstate] => HY000 [id] => 16 ) [1] => iiss [2] => 5744 [3] => 5709 [4] => 제목 없음 [5] => 20170214160234 )


xe 는 최신버전이고, 누리고 쇼핑몰은 최신버전 nurigo-1.1.17 적용해보고,
하위버전(1.1.11)설치해 봐도 같은 증상입니다.

호스팅을 이용하고 있고, 서버 정보는 아래와 같습니다.
app : Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips DAV/2
 xe_version : 1.8.29
 php : 5.6.7
 db_type : mysqli
 use_rewrite : Y
 use_db_session : Y
 use_ssl : none
