### ISSUE TITLE
위시리스트 썸네일 함수 오류

### ISSUE THREAD

**Issue by treasurej** [bjrambo/nurigo#126]
favoriteitems.html 파일에
기존 {$val->getThumbnail()} 함수를 {$val->thumbnali} 함수로 변경되었더라구요.
함수가 변경되서 기존 스킨에서는 오류가 나지만,
더 중요한 건 thumbnali 에 오타가 있네요^^;
썸브날리(thumbnali) -> 썸브네일(thumbnail)로 변경해 주세요~
그리고, 이 함수가 위시리스트에서만 변경되었나요, 아니면 또 변경해야 하는 스킨이 있나요?

**Comment by bjrambo** [comment]
위시리스트와, 장바구니를 담당하는 cartitem리스트를 확인해보시면 됩니다.
