### ISSUE TITLE
람보님, 이니시스 웹표준 휴대폰소액결제 설정창 오류입니다.

### ISSUE THREAD

**Issue by kimbumjin** [bjrambo/nurigo#131]
휴대폰 소액결제창에서 (실물/컨텐츠) 옵션이 무조건 컨텐츠로 등록되어 버립니다.
자세한 질문은 xetown 에 남겼습니다.
확인 부탁드리겠습니다 ㅠㅠ
https://www.xetown.com/qna/501886

**Comment by kimbumjin** [comment]
람보님 해결했습니다!

**Comment by bjrambo** [comment]
혹시 해결하실때의 방법이 어떻게 하신건가요? 제공 해주시면 확인후 더 나은 방법이나 안내를 도와드릴게요...

제가 어제 오늘 내일 모래 다 외출중이라서 재대로 못봐드려서 ㅜㅠ 죄송합니다.

**Comment by kimbumjin** [comment]
아 지금 집에 와서 확인했습니다.
이니시스 웹표준 모듈에 inipaystandard.view.php 파일을 열어서요

Context::set('payment_method', $payment_method);
               if($this->module_info->method_mobilephone == 'Y'){$HPP = '1';}
               if($this->module_info->method_mobilephone == 'M'){$HPP = '2';}
		$acceptmethod = sprintf("HPP(%s):Card(0):OCB:receipt:cardpoint", $HPP);

저 부분에서 윗줄  if($this->module_info->method_mobilephone == 'Y'){$HPP = '1';}
를 지우고 밑에 HPP(%s) 를 HPP(2) 로 고정시켜봤습니다.

제가 알아보니깐 핸드폰 모듈 1번이 컨텐츠설정이고 2번이 실물설정이라고 하더라구여
이렇게 하니깐 설정상관없이 실물로 등록이 되어서 결제가능했습니다^^

**Comment by kimbumjin** [comment]
아 지금 집에 와서 확인했습니다.
이니시스 웹표준 모듈에 inipaystandard.view.php 파일을 열어서요
 
Context::set('payment_method', $payment_method);
 if($this-&gt;module_info-&gt;method_mobilephone == 'Y'){$HPP = '1';}
 if($this-&gt;module_info-&gt;method_mobilephone == 'M'){$HPP = '2';}
 $acceptmethod = sprintf("HPP(%s):Card(0):OCB:receipt:cardpoint", $HPP);
 
저 부분에서 윗줄  if($this-&gt;module_info-&gt;method_mobilephone == 'Y'){$HPP = '1';}
를 지우고 밑에 HPP(%s) 를 HPP(2) 로 고정시켜봤습니다.
제가 알아보니깐 핸드폰 모듈 1번이 컨텐츠설정이고 2번이 실물설정이라고 하더라구여
 이렇게 하니깐 설정상관없이 실물로 등록이 되어서 결제가능했습니다^^
 
 
-----Original Message-----
