### ISSUE TITLE
람보님, 밑에 treasure J 님께서 올려주신 오류 부분 질문입니다.

### ISSUE THREAD

**Issue by kimbumjin** [bjrambo/nurigo#132]
이번에 올려주신 이니시스 웹표준 수정버전은 새로 설치하였습니다.
(휴대폰 결제부분도 제대로 설정이 되더군요!)

그런데 마일리지 적용 후 결제수단 정해서 클릭하면 다음으로 뜨는 화면에서는 마일리지 적용이 안된 화면이 뜨는 부분은 아직 오류가 있습니다.
제가 일전에 conory 님 사이트에다가 글도 올리긴 했었습니다만 (https://www.conory.com/qna/65474)
화면으로 스샷 캡쳐해서 다시 올려보겠습니다.

**사진 1**
![mileage_check01](https://cloud.githubusercontent.com/assets/25459002/23092673/f9300638-f613-11e6-8bd3-d49729697c9d.jpg)

**사진 2**
![mileage_check02](https://cloud.githubusercontent.com/assets/25459002/23092674/fd3b855e-f613-11e6-907f-ef3413153baa.jpg)

**사진 3**
![mileage_check03](https://cloud.githubusercontent.com/assets/25459002/23092675/ff65cf6a-f613-11e6-8f9f-5e0c586bfc49.jpg)

올린 화면 순서대로 마일리지 적용한 후 결제수단 클릭(화면1) 하면
다음 페이지(사진2)로 넘어가는데, 이때 보여지는 화면에는 마일리지가 전혀 적용이 안된 상태로 나옵니다.
그리고 여기서 다시 결제하기를 클릭하면 다음 페이지(사진3) 으로 이니시스웹표준 설정창이 올라오는데요, 이때는 마일리지가 적용된 가격으로 나오긴 합니다.

혹시 손님분들이 계산하시다가 2번 화면 창에서 마일리지가 적용안된줄 알고 왼쪽 돌아가기 버튼을
계속 누르게 될 수도 있어서 글 남깁니다.
저는 제 사이트에 공지사항으로 올려놓긴 했습니다만 꼭 고쳐질 수 있는 부분이면 좋겠습니다.
확인 부탁드리겠습니다. 감사합니다!

**Comment by kimbumjin** [comment]
람보님 혹시 확인 되신부분이신가요? 확인 여부라도 알려주시면 감사하겠습니다..

**Comment by bjrambo** [comment]
아직 작업이 안됫어요.
이번주 다음주 바빠서.. 이번달 말에 패치될것 같아요. 죄송합니다.

**Comment by kimbumjin** [comment]
넵 감사합니다!!
