### ISSUE TITLE
ADMIN 에서 각 모듈로 연결 에러가 납니다.

### ISSUE THREAD

**Issue by dokdolove** [bjrambo/nurigo#138]
안녕하세요?
기본, 필수 모듈을 모두 설치를 하고 설치된 모듈로 가서 CYMPUS를 클릭하면
index.php?module=admin&act=dispCympusadminIndex 의 ADMIN 페이지로 이동은 되는데요,
기타 메뉴(상품관리, 결제관리,마일리지....)의 연결은 되지 않습니다.
예) 상품관리 클릭하면 www.mydomain.ca 페이지가 작동하지 않음 (HTTP ERROR 500)
상단 링크 주소는 /index.php?module=cympusadmin&act=dispNproductAdminModInstList 입니다.
물론, 설치된 모듈에서 개별적으로 클릭하면 해당 모듈이 실행이 되는데요,
ADMIN 페이지에서 각 모듈로는 에러가 납니다.
ADMIN과의 연결 방법이 따로 있는 건가요?

**Comment by bjrambo** [comment]
최신버전 업데이트하세요.
