### ISSUE TITLE
리스트 항목에서 체크 버튼 여러개 선택 한 후 장바구니에 담으면 담기지 않습니다.

### ISSUE THREAD

**Issue by bazakorea** [bjrambo/nurigo#140]
안녕하세요.

여기 장바구니 담기는 부분 알려주시면 좋겠습니다.

담긴다는 메시지는 뜨는데 가보면 않보입니다.

개별로 담는 건 잘 됩니다.

https://www.xpressengine.com/index.php?mid=qna&search_target=title_content&search_keyword=%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88&document_srl=23076281

**Comment by bjrambo** [comment]
- 보류
