### ISSUE TITLE
cympusadmin페이지에서는 파일첨부가 안되는 증상

### ISSUE THREAD

**Issue by artistudy** [bjrambo/nurigo#141]
라이믹스 1.8.32 + php 7.0 (카페24) + 누리고 최신일 때
cympusadmin페이지에서는 파일첨부가 안되는 증상이 있습니다.
꾀 이전버전부터 계속 생긴 문제고..

common/js/plugins/jquery.fileupload/js/main.js
modules/editor/skins/ckeditor/file_upload.html 이 두개의 파일을 라이믹스 1.8.24 버전으로 바꿔주니
해결이 됩니다.

**Comment by bjrambo** [comment]
mid값이 누락되어서 그런지 추후 테스트해볼 필요성.

**Comment by bjrambo** [comment]
파일 첨부 관련 문제 고쳐놨습니다.
이번 버전 나오면 업데이트 다 해보시고 혹시 안되는 부분이 있다면 또 재보 부탁드립니다.
