### ISSUE TITLE
통화설정을 미국 달러로 할 경우 상세페이지 합계 단위 "원"단위로 표시되는 문제

### ISSUE THREAD

**Issue by treasurej** [bjrambo/nurigo#142]
통화설정을 미국 달러로 할 경우
상품상세페이지(modules/nproduct/skins/스킨/itemdetail.html)에서
옵션이 있을 경우
"합계"가격과 "옵션 선택 후 합계" 가격이 달러로 적용되지 않는 문제

참고 페이지(현재 달러로 해 놓은 상태)
http://shopxe.co.kr/test2/goods/159
합계표시금액, 옵션선택후 합계표시금액이 "원"단위인 것 같습니다.

기본스킨에서도 같은 증상입니다.

**Comment by bjrambo** [comment]
#143
