### ISSUE TITLE
epay모듈 모바일 스킨 지정 안되는 문제.

### ISSUE THREAD

**Issue by artistudy** [bjrambo/nurigo#146]
epay 모듈 모바일 스킨 지정이 안되는 문제가 있습니다.
누리고,라이믹스 둘 다 최신버전이고 PHP7.0입니다.

**Comment by bjrambo** [comment]
누리고 1.1.17 , 라이믹스 1.8.34 , php 7.0 (cafe24)입니다.
완전 다 삭제하고 깨끗한 상태에서 재설치 해보아도 동일한 문제가 발생해서
다시 이슈 남깁니다.

epay모듈의 경우 모바일 스킨이 지정되지 않아, 모바일에서도 자꾸 PC버전
결제 선택박스(신용카드,실시간 계좌이체,가상계좌,휴대폰 선택하는 박스)가 떠서 모바일 결제가 불가능합니다.
이거 스킨만 안불러오는게 아니라 선택된 결제정보도 pc껄 불러와버리네요.
그니까, 모바일 설정이라고 되어 있는 부분은 설정 해주나 마나 적용이 안되고
그냥 pc설정껄 다 불러와버리네요..
