### ISSUE TITLE
결제 완료시 서버오류

### ISSUE THREAD

**Issue by artistudy** [bjrambo/nurigo#147]
https://www.xetown.com/index.php?&mid=xepoint&search_keyword=%EC%9D%B4%EB%8B%88%EC%8B%9C%EC%8A%A4&search_target=title_content&document_srl=160902

누리고 이니시스 웹표준 결제 모듈 사용중이고
누리고 최신, 라이믹스 최신입니다.
결제 완료시 결제는 완료 되고 주문도 완료는 되는데
결제 완료창이 뜨는게 아니라 서버 오류창이 뜹니다.

**Comment by bjrambo** [comment]
xe 1.8.15 이상 사용하신다면 다음커밋의 수정사항을 거쳣는지 확인해보세요.
https://github.com/conory/rhymix/commit/a519db608dfa8d5b1f6825206836820e64de20ec
