### ISSUE TITLE
주문시도시,장바구니 비었을 시 서버오류 발생하는 문제

### ISSUE THREAD

**Issue by artistudy** [bjrambo/nurigo#148]
저번부터 계속 있었던 문제인데
주문 시도시, 장바구니에 아무것도 담겨있지 않을시 서버오류가 발생하고

이건 누리고 1.1.12버전의 nproduct.item.php를 덮어씌우면 해결됩니다...

**Comment by artistudy** [comment]
이거 스킨만 안불러오는게 아니라 선택된 결제정보도 pc껄 불러와버리네요.
그니까, 모바일 설정이라고 되어 있는 부분은 설정 해주나 마나 적용이 안되고
그냥 pc설정껄 다 불러와버리네요..

**Comment by bjrambo** [comment]
fixed d95856c

**Comment by bjrambo** [comment]
장바구니 비어있으면 서버오류 뜬다고 하셧는데 스킨을 어떤거 쓰시나요?

**Comment by artistudy** [comment]
트렌디샵 스킨을 쓰는데, 
기본스킨이나 메리제이 스킨같은걸 써도 동일한 문제가 발생해서 이슈로 등록했습니다.
fixed d95856c 적용하니 문제 해결되었습니다. 감사합니다 :)
