### ISSUE TITLE
메인진열 카테고리에 상품이 안담깁니다.

### ISSUE THREAD

**Issue by freeman1026** [bjrambo/nurigo#15]
안녕하세요. 

1.5.2 개선사항
•XE 1.7.4 에서 메인진열 카테고리에 상품이 안담기는 문제 수정 됐다고 봤습니다.

지금 환경은 아래와 같습니다.
app : Microsoft-IIS/7.5     /   xe_version : 1.8.15    /    php : 5.3.27      /   db_type : mssql

지금 1.8.15 인데 모든 기능은 다됩니다. 메인진열 카테고리에 상품을 담을려고 화살표를 눌러도
아무런 반응이 없습니다. 카테고리는 다 만들고 코드까지 스킨에 다등록하고 했는데 눌러도 아무런
반응이 없네요.

**Comment by qw5414** [comment]
증상확인해볼께요..

**Comment by qw5414** [comment]
안녕하세요. 말씀하신 기능이 다음과 같은 기능으로 보여지는데, 
http://docs.nurigo.net/?page_id=61
혹시 이 기능이 맞다면, 해당 기능의 작동이 어디 부분에서 어떻게 막히는지, 등등 이미지첨부와 함께 보여주신다면 고치는데 많은 도움이 될것 같아요 !

**Comment by freeman1026** [comment]
리플감사합니다. 증세는 보내주신 링크에서 "상품진열" 에서 1번까지는 했습니다. 여기서 2번을 클릭을 하면 하단으로 1번 best 카테고리로 상품이 내려가야 하는데 2번 ▼ 을 클릭을 해도 아무런 반응이 없습니다. 상품이 밑으로 내려가지도 않고 눌러도 아무런 반응도 없네요.

**Comment by qw5414** [comment]
@freeman1026 오늘 첫 배포날이라, 오늘 배포되는 버전에서는 해결되지 않은 버전으로 배포가 이루어질 것입니다.
다음 배포시즌인 2월 28일쯤 확인해주세요.

**Comment by bjrambo** [comment]
@freeman1026 정상작동확인이 되고 잇습니다.
혹시 문제되는 서버의 사이트를 알려주시면 확인해보도록 하겠습니다.

문제되는 사이트의 관리자 아이디, 비밀번호 FTP접속 정보와 함께,
qw5414@naver.com 으로 남겨주세요

**Comment by bjrambo** [comment]
피드백이 없어서 일단 닫아 두겠습니다.
개인적으로 피드백을 원하시면 qw5414@naver.com 에서 부탁드려용
