### ISSUE TITLE
옵션이 있을때 옵션 적용 가격의 원화 표시 문제

### ISSUE THREAD

**Issue by dokdolove** [bjrambo/nurigo#159]
안녕하세요? 이슈 등록을 하나씩 해야 된다고 해서 개별적으로 작성합니다.
기본적으로 통화설정에서  미국 달러$ 로 변경하고 $1,234.00 형식으로 설정이 된 상태입니다.

1. 옵션가격 합계의 원화 표시
샘플페이지에서 볼 수 있듯이, 상품 가격과 옵션가격은 $ 달러로 표시가 되는데요, 
옵션 적용 합계 가격은 여전히 한화 형태로 표시가 됩니다. (18,999원 - 컴마와 소숫점 오류)
옵션중에 '블랙/S사이즈(**+10,000**)' 라고 되어 있는데 **+100.00** 이 맞는것 같습니다.
아래 그림에서 알 수 있듯이 옵션 적용시
블랙/S사이즈(**+10,000**)   /   1 개	/    	**18,999**  ◀ 금액 표시가 189.99 또는 $189.99 가 정상인듯합니다.
옵션적용시의 금액은 한화 형태로 나오는데 맨아래의 합계는 달러로 $189.99 정상적으로 표시가 됩니다. 

![1111](https://cloud.githubusercontent.com/assets/25971284/24871246/3afc146e-1dd6-11e7-8aba-4eabbed54c49.jpg)

**Comment by bjrambo** [comment]
fixed https://github.com/bjrambo/nurigo/commit/90a091ca3ce8aa93f402945d837b77e52f97c0d5
