### ISSUE TITLE
reviewform.html 화면 들어가자마자 결제내역에...

### ISSUE THREAD

**Issue by treasurej** [bjrambo/nurigo#16]
이니시스 카드결제나 실시간계좌이체 등 플러그인이 아닌 결제모듈로 결제하기 하면
ncart/skins/스킨/reviewform.html 화면이 나오는데
벌써 여기서부터 "누리고 관리자 - 결제관리 - 결제내역"으로 들어가 버림.

원래는 reviewform.html 화면에서 결제하기를 하면 이 때 이니시스 결제창이 뜨는데
이 창에서 결제진행을 완료하거나 취소한 결과가 나온 후에
"누리고 관리자 - 결제관리 - 결제내역"으로 들어가는 게 정상임.

결국은 reviewform.html 화면에서 새로고침 하면 계속 "결제내역"으로 들어가는 문제도 함께 일어나게 됨.

**Comment by bjrambo** [comment]
. . . ...
이걸 어떻게 구현해야할까요.

일딴 테스트 계정이 설치된 공간에서는..

상품 장바구니까지 접근이 된상태까지는 가능햇는데, 결제하기 버튼에서 클릭시 orderitem이 없다는 오류가 뜨더라구요..

그래서 일딴 카메론에서 확인해봤는데, 카메론에서는.. 말씀하신것처럼 작동이 바뀌거나 그런게 없는거같아서요..(취소한 건에 대해서 취소되었습니다 라고 알려주고 누리고관리자인 결제내역으로 들어가는것 같진 않았습니다..)

**Comment by bjrambo** [comment]
어라.. 최신버전으로 넘겨놓으니, 일딴 문제구현 서버타임아웃 문제점 구현은 안되고 DB속 입력 되는 문제점을 확인해보도록 하겠습니다.

**Comment by bjrambo** [comment]
`벌써 여기서부터 "누리고 관리자 - 결제관리 - 결제내역"으로 들어가 버림.` 이라고 말씀하신건, 결제의 기록이 거기에 남는다는거죠? 리다이렉트으로 접속되는것이 아니라..

**Comment by treasurej** [comment]
네 맞습니다~

**Comment by bjrambo** [comment]
작동 오류 원인 파악.
epay에서 reviewform.html 을 호출하는 트리거가 실행되는 과정 이전에 이미 결제 진행되었다고 기록을 해버림, 해당 부분을 리버뷰중에서는 결제 중이라고 기록 하도록 하고, 이 이후 취소, 결제완료 등등으로기록을 할 수 있도록 수정해보도록 하겠습니다.

**Comment by bjrambo** [comment]
fixed in https://github.com/bjrambo/nurigo/commit/3a84ff77653c375156401611433c9952dddf9d21
