### ISSUE TITLE
배송비 착불 선택시 원화로 바뀌면서 달러표기가 사라지는 문제

### ISSUE THREAD

**Issue by dokdolove** [bjrambo/nurigo#160]
2. 배송비 결정할 때  '선결제'와 '착불' 선택시 원화로 바뀌는 현상
옵션이 적용되거나 되지 않아도 결제화면에서 배송비 선결제/착불 선택시에
이미 클릭되어진 '선결제'를  '착불'로 클릭하게 되면 
제대로 나왔던 $달러 표시의 금액이 갑자기 원화 형태로 바뀌어 버립니다.
아래 샘플 이미지에서도 보시듯이 처음엔 $194.99 가 맞게 표시 되지만 '착불'을 한 번이라도
클릭하게 되면 18,999 의 원화 형태로 바뀌고(정상은 $189.99) 다시 '선결제'를 클릭하게 되면 
배송비가 $5.00 달러에서 500원 형태로 바뀌면서 합계는 19,499 의 원화 형태로 바뀝니다.
정상은 $194.9 라고 표시가 되어야 맞는것 같습니다.
![2222](https://cloud.githubusercontent.com/assets/25971284/24871299/5f608650-1dd6-11e7-8ec5-1dd3d29b502c.jpg)

![3333](https://cloud.githubusercontent.com/assets/25971284/24871319/76c90e5c-1dd6-11e7-90e3-71482f913c60.jpg)

![4444](https://cloud.githubusercontent.com/assets/25971284/24871324/79a4c18e-1dd6-11e7-8440-1afbdf0bc263.jpg)

**Comment by bjrambo** [comment]
fixed https://github.com/bjrambo/nurigo/commit/eb5f48c365b5c7281fe237ae02c4f73725287808
