### ISSUE TITLE
섬네일 부분 확인부탁드려요.

### ISSUE THREAD

**Issue by wngud2003** [bjrambo/nurigo#167]
현재 섬네일부분에 이미지를 등록, 상세내용에 내용등록

이렇게 지정이 될경우 로딩.. 관련 에러발생

섬네일 이미지등록 상세내용에 다른이미지 2개추가시
섬네일 무시 다른이미지 2개중 첫번째 사진이 섬네일로 대체

이부분 확인부탁드립니다

**Comment by bjrambo** [comment]
관련 오류가 나타나지 않습니다.
정확한 오류증상이 어떤 메세지를 발생되게 하는지 알려주세요..
