### ISSUE TITLE
모바일 reviewform.html이 m.skins 에서가 아닌 skins 에서 불러와지는 문제

### ISSUE THREAD

**Issue by treasurej** [bjrambo/nurigo#17]
모바일에서 reviewform.html(결제화면)이 m.skins 에서가 아닌 skins 에서 불러와지는 문제

**Comment by qw5414** [comment]
리뷰폼이 보니깐, 트리거에서 실행되도록 되어있는 상태입니다.
모바일여부인지 확인하는 함수를 사용하여, m.skins에 별도로 꾸미고 할 수잇도록 추가하는 편이 나을것 같기도 하네요

**Comment by bjrambo** [comment]
fixed in https://github.com/bjrambo/nurigo/commit/924c03affc2ab7d391a03ff0e482fb0fb56dd5e9
