### ISSUE TITLE
택배사 - KG로지스 추가 건

### ISSUE THREAD

**Issue by eondcom** [bjrambo/nurigo#175]
\www\modules\ncart\ncart.class.php
54라인
'61' => 'KG로지스'
80라인
'61' => 'http://www.kglogis.co.kr/delivery/delivery_result.jsp?item_no='

\www\modules\nstore\nstore.class.php
54라인
'61' => 'KG로지스'
80라인
'61' => 'http://www.kglogis.co.kr/delivery/delivery_result.jsp?item_no='

이렇게 혹시 추가 가능한지요?;
번호는 아무렇게나 하셔도 되고;;

**Comment by mothercat** [comment]
감사합니다^0^!
