### ISSUE TITLE
'카트' 주문서 작성시 주소값이 넘어가지 않는 문제

### ISSUE THREAD

**Issue by firstflower** [bjrambo/nurigo#185]
요점 : 상품 주문시 주소 검색버튼를 클릭후 다음 우편번호 서비스 창에서 주소 검색시 지번이 2개 이상일 경우 주소 값이 넘어오지 않아 결제하기 진행이 안되는 현상

카트에서 배송지정보 주소 검색을 하기 위해 다음주소 검색창에서 
검색단어 => 백양대로78
검색하면 아래와 같은 검색결과가 나옴니다

![01](https://user-images.githubusercontent.com/29632577/27441958-edefdd78-57a9-11e7-8e15-ec054d50b166.PNG)

여기서 1번, 2번 주소지를 잘 보시면 

1번은 지번이 1개
2번은 지번이 2개가 있습니다.

검색 주소중 1번을 선택하여 결제하기 버튼을 클릭하며 아무문제가 발생하지 않고 다음으로 넘어가 결제를 진행 할 수 있습니다.
![02](https://user-images.githubusercontent.com/29632577/27443066-f98867c4-57ac-11e7-86de-83c59b45701b.PNG)

**하지만 문제점 오류는 주소 2번을 선택할 경우 다음으로 진행 하지 못하는 사항이 발생합니다.**

![03](https://user-images.githubusercontent.com/29632577/27443094-10b086b6-57ad-11e7-860b-d20ae842b31a.PNG)

![04](https://user-images.githubusercontent.com/29632577/27443104-170bd966-57ad-11e7-89c4-84acd44712af.PNG)

![17ef912454a3523b4b1f89d74198db8f](https://user-images.githubusercontent.com/29632577/27443317-a2bdd07c-57ad-11e7-87b1-ca376b22885b.png)
![6438078fb32cd606e9e3cb096367f1bc](https://user-images.githubusercontent.com/29632577/27443316-a2b59eac-57ad-11e7-889c-24393065763e.png)

**Comment by bjrambo** [comment]
Fixed in 339639332c7783a72041fa3b6467029b5435fe80
