### ISSUE TITLE
상품 상세페이지의 옵션 부분 개선

### ISSUE THREAD

**Issue by andjfrrk** [bjrambo/nurigo#186]
현재 옵션 상품이 있을 경우, select 아래에 옵션 내용이 표시 될 div가 작게 표시되고 있습니다.
또한, 옵션 선택 후 다시 삭제해서 선택한 옵션이 없을 경우 상품 합계가 계속 남아 있고요.

이 부분에 대해 개선한 내용입니다.
스킨은 shopping을 기준으로 했으며, 변경한 파일을 아래와 같습니다.
/nproduct/skins/shopping/itemdetail.html
/nproduct/tpl/skin.js/itemdetail.js
[nproduct.zip](https://github.com/bjrambo/nurigo/files/1101901/nproduct.zip)

**Comment by bjrambo** [comment]
`/nproduct/tpl/skin.js/itemdetail.js`파일의 경우 누리고 전체 스킨에 영향을 줄 수 있는 부분이 됩니다.

함부로 마음대로 모든 동작에 맞다고 판단하고 변경이 힘들어요. 

최대한 검토해본다음 전체적인 스킨에 이상이 없는지 확인하고 적용할 예정입니다. 

원하는 답변이 되어드리지 못해서 죄송합니다.

**Comment by bjrambo** [comment]
죄송합니다. 추가할 수 없을 것 같스빈다.
