### ISSUE TITLE
카트 중복입력 해결해주시면 감사드리겠습니다.

### ISSUE THREAD

**Issue by for2gles** [bjrambo/nurigo#194]
이미 이슈되어있는데 밑으로 내려가있길래 다시 올려봅니다.

**Comment by bjrambo** [comment]
이슈가 열려있는것에 대해서 중복적으로 이슈를 다시 달 필요는 없습니다. 중복으로 들어오는건 오히려 프로젝트에 방해가 될 수 있어요... 이점 생각해주셧으면 좋겠습니다.
