### ISSUE TITLE
주문 결제시 관리자에게 알림 기능 보내기

### ISSUE THREAD

**Issue by eondcom** [bjrambo/nurigo#196]
주문 결제 확인하면 관리자에게 메일이나 카톡 등으로 알림 기능 보내기 가능할까요?

**Comment by eondcom** [comment]
1. 쇼핑몰 결제알림(상품주문알림, paynoty) 라는 모듈이 있었군요.
현재는 메일/문자만 가능한데 혹시 카카오톡으로도 알림을 받을 수가 있을까요?

2. 그리고, 지금 정상적으로 동작하는 게 맞는지요?
전송방식을 이메일이나 문자+이메일로 해도 이메일로 전송이 안되는데,
무슨 문제일지 어떻게 알아볼 수 있을까요?

제 vps 서버 문제일까요?
음.. 

3. 그리고 보내는 휴대전화번호와 받는 휴대전화번호는 무엇인지요.
관리자가 받는 것을 염두에 두고, 보내는 번호와 받는 번호를 임의로 지정하면 되는 건가요?

**Comment by bjrambo** [comment]
1. 알림톡 기능은 지원하지 않지만 알림톡을 대신하는 플러스친구를 친구추가한 유저들에 한해서 보내는 친구톡 기능을 이용할 수 있습니다.

2. 정상적으로 작동하였으나 조건이 ncart의 전화번호의 필드 네임이 `tel1` 일경우에만 작동했던것으로 보여집니다. (이 기능은 원래 3번에서 질문한 관리자에게만 보내는 기능을 확장하여 회원전화번호 필드의 전화번호 혹은 입력한 전화번호의 경우 작동하도록 되어잇었습니다.) 그래서 이경우 다시한번 설정페이지에서 ncart에서 설정한 mid마다 설정값이 추가되도록 되어있으니 각각 설정을 따로 해주시길 바랍니다.

3. 보내는 휴대폰 전화번호는 coolsms에서 등록한 전화번호(발신이 가능한 전화번호를 인증 받아야지 정상적으로 이 시스템을 이용할 수 있습니다. 그런 인증받은 전화번호를 입력하시면됩니다.)를 입력하셔야 하고 받는 전화번호의 경우 위의 설정처럼 일반 유저들에게 제공하지 않을시 관리자로써 받을 전화번호를 입력하시면 됩니다.

**Comment by bjrambo** [comment]
fixed in https://github.com/bjrambo/nurigo/commit/90db4e5cb55e33dc1a5ece9a96ac71f9931e132b

**Comment by eondcom** [comment]
이해가 잘 안되네요.
2번부터 일단 살펴보면,
말씀하신 ncart가 장바구니 모듈 맞나요?
장바구니 모듈에서... 전화번호 필드 네임 설정하는게 따로 안 보이는데...
cart 모듈 > 관리 > 
페이지설정/결제폼관리/스킨설정/모바일스킨
이렇게 있는데,
![image](https://user-images.githubusercontent.com/3683813/28247726-70e1d662-6a71-11e7-8c7f-aa89f1eaaeca.png)
필드추가로 위와 같이 설정하면 되는 건가요?
굳이 저렇게 해야할까요.
그냥 저런 설정 없이도  paynoty(쇼핑몰결제알림)에서 설정한 게 있으면 동작하도록 하는게 좋지 않을까요?

**Comment by eondcom** [comment]
저렇게 설정해도 메일이 안오네요;ㅁ;

**Comment by bjrambo** [comment]
그러니깐 tel1일 필요가 없도록 develop에 패치 해드렷다고요..

**Comment by bjrambo** [comment]
메일은 또 왜안되시징..;;

**Comment by bjrambo** [comment]
메일은 회원에게 보내는 메일관련 설정이 전혀 없습니다.

(애초에 비회원의 경우 메일정보를 입력 받지도 않았으니..)

그래서 해당 부분의 메일정보는 앞으로도 지원은 안할것 같고요, 전화번호를 이용한 친구톡 + SMS서비스만 회원에게 가는거고요, 이메일의 경우 그냥 관리자용으로 발신자와 수신자에 사용하시는 이메일 쓰시면 정상적으로 발송되는걸 확인했습니다.

**Comment by eondcom** [comment]
develop에 패치된 paynoty 모듈을 새로 업로드하고 적용 후 확인해보니 정상적으로 메일 발송이 되었습니다.
감사합니다.

지메일, 네이버, 다음 메일로 테스트해보았습니다.
네이버, 다음의 경우 정상적으로 메일 수신이 되었습니다만,
지메일(eond@eond.com)은 메일 수신이 되지 않았습니다.

이건 왜 그럴까요..

**Comment by bjrambo** [comment]
일부메일링에 문제가 있는것으로 보여지는데요. 발신이메일로 수신거부 이유가 나오니 발신메일을 수신가능한 메일로 한다음 실패사유을 알아보세요
