### ISSUE TITLE
이런 에러가 뜹니다... ㅠㅠ

### ISSUE THREAD

**Issue by k2hnice** [bjrambo/nurigo#197]
얼마전 문의 드렸던 사람입니다.
그림에서 보시는 바와 같이....
이름과 주소를 입력해도 주소 또는 이름...에 값을 입력하세요. 라고 뜹니다.
토탈커맨더로 스킨파일을 올리다 보니 누락되는 파일이 있을까 싶어서..
파일질라로 다시 업로드 하였습니다.
문제가 무엇인지 답변 부탁드립니다.
감사합니다.

**Comment by bjrambo** [comment]
혹시 모든 누리고 모듈의 파일을 업데이트 같이 해주신거 맞으신가용?

혹시 오류가 일어난 주소의 검색 키워드를 알려주시면 확인해보도록 할께요 ㅎ

**Comment by bjrambo** [comment]
최신버전에서 문제가 재현되지 않고 오랫동안 피드백이 없어 이슈는 일단 닫아두도록 하겠습니다.

문제가 있으면 다시한번 이슈를 열어서 알려주십시오.
