### ISSUE TITLE
옵션 가격 추가시, 최종 결제금액 0 제외현상 [버그]

### ISSUE THREAD

**Issue by wngud2003** [bjrambo/nurigo#202]
<img src="http://i.imgur.com/XsV99f7.jpg">
<img src="http://i.imgur.com/In1Obmv.jpg">

보시는 바와 같이, 해당 상품의 상세 페이지내에서는 정상적으로 옵션 가격이 출력되고있습니다.
(누리고 최신버전으로 업데이트 된 상태)

그러나, 구매창으로 넘어가면 최종가격에서 0이 하나 빠진상태이며 가격이 따로 놉니다..

이부분 버그현상이지 않을까 싶은데, 조급한 해결 부탁드립니다 ㄷㄷ;;

**Comment by bjrambo** [comment]
구매옵션에 타입항목설정에서 고정으로 하시면 해당 추가 옵션 110000만원에 대한 가격만 책정됩니다.

0이 빠진게 아니라 고정옵션으로 인한 문제로 보여집니다.

없음으로 선택한다음 가격이 추가되도록 해보세요.

**Comment by bjrambo** [comment]
이 이슈에서는 고정에 대한 옵션을 지정되었을때 가격책정 방식에 대한 부분을 고치는걸로 하겟씁니다. 닫지말아주세요.

**Comment by wngud2003** [comment]
운영중인 쇼핑몰인데, 답변 빠르게해주셔서 감사합니다.
빠르게 처리가 되어서 다행입니다 ㅜㅜ
