### ISSUE TITLE
결제오류가 발생하는데 확인 가능하실까요?

### ISSUE THREAD

**Issue by for2gles** [bjrambo/nurigo#204]
카메론측에 문의했을때 스킨과 누리고에는 문제가 없다는데 이니시스 테스트계정에서도 오류가나고 저희 계정에서도 오류가 나거든요. 테스트모듈에서 오류가나는거 한번 확인해주실 수 있나요?

mid=inipay_std&act=procInipaystandardDoIt 이곳에서 서버오류가 발생합니다

**Comment by bjrambo** [comment]
XE를 라이믹스로 업데이트 하시거나, 
https://github.com/conory/rhymix/commit/a519db608dfa8d5b1f6825206836820e64de20ec
아래와 같이 코어를 수정하셧나요?

**Comment by for2gles** [comment]
라이믹스를 이용하고있습니다. 이니시스 전화해보니까 내부서버오류는 이니시스문제가 아니라고하네요.

**Comment by bjrambo** [comment]
서버오류 어떤종류인지 모르겠으나 500에러라면 서버 에러 로그항목을 알려주세요.

**Comment by for2gles** [comment]
에러목록은 잘 모르겠네요.. 모르겠어요 서버오류라고만 뜨니..

**Comment by bjrambo** [comment]
qw5414@naver.com 으로 로그인 정보랑 FTP좀 알려주세요

**Comment by for2gles** [comment]
보냈습니다

**Comment by bjrambo** [comment]
cafe24인가요?

**Comment by for2gles** [comment]
네 맞습니다

**Comment by bjrambo** [comment]
cafe24 특성인거같은데요 ㅡ.ㅡ; 다른 호스팅을 이용하는 저는 문제 없는데 카페24에서만 생겨나고 있어요..ㅠㅠ 일단 이부분은 cafe24측에 문의남겼습니다.

**Comment by for2gles** [comment]
아 그러면 호스팅을 옮겨야하나요?? cafe24 쓰시는 다른분들도 이런게 있으신가요??

**Comment by bjrambo** [comment]
@for2gles 제 계정도 동일하게 오류나고 있습니다.

다만 메세지모듈의 스킨이 다르다보니 해당 오류내용이 원래는 떠야하는데 for2gles에서는 안뜨는 겁니다

라이믹스는 해당 서버오류가 있을때에도 어디에서 오류가 나는지를 상세하게 위치도 알려주는데 해당 변경하신 스킨이 XE기준이라 그 내용이 없이 그냥 서버 오류라고 떠서 알수 없었던거죠..;ㅁ;

암튼 cafe24측에 문의의 대한 답변이 와야 합니다..

**Comment by for2gles** [comment]
아 그런가요? 그러면 추천하시는 호스팅 있나요? 루아틱으로 옮겨야하나 생각하는데.. 해당 사항으로 환불이 가능할까요?? 뭐라고 문의를 넣어야 환불을 해줄지..
