### ISSUE TITLE
합동택배 추가 부탁드려요

### ISSUE THREAD

**Issue by for2gles** [bjrambo/nurigo#206]
합동택배 추가 부탁드립니다
http://www.hdexp.co.kr/deliverySearch2.hd?barcode=
이방식 말고 페이지게 뜨게좀 해야하는데 난감하네요..

**Comment by for2gles** [comment]
https://www.allssu.co.kr/hdexp/hdexp.php?item_no=3207103306794 직접 만든걸로 새창 띄우기로 사용 가능한가요?

**Comment by bjrambo** [comment]
구현방식에 따라 지원여부를 결정할 수 잇을것 같아요..

**Comment by for2gles** [comment]
마음대로 파싱해서 만들어도 되는건지 모르겠지만 초보가 머리싸매가면서 만든건데 한번 봐주세요.
`<?php

$item_no = $_GET['item_no'];
$url = 'http://www.hdexp.co.kr/deliverySearch2.hd?barcode='.$item_no; //정보 링크
$text = file_get_contents($url); //코드 가져오기
$standard = '/":"([^"]+)"/'; // 정규식
$standard_product_count = '/"cnt":(.),"/';
preg_match_all($standard, $text, $match); // 파싱(array로 배열)
preg_match_all($standard_product_count, $text, $product_count); // 파싱(array로 배열)
$list_count = count($match[1]); //array 개수 카운트
$branch_start = $list_count - '1';
$item_srl = $list_count - '2';
$reciever = $list_count - '3';
$sender = $list_count - '4';
$prod = $list_count - '5';
$branch_end = $list_count - '6';
//$test = item_detail('prod');


?>

<!doctype html>
<html >
<head lang="ko">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>합동택배 배송조회</title>
</head>
<body style="font-family:Nanum Barun Gothic, sans-serif; font-size:12px; ">

<table border="0" cellspacing="0" cellpadding="3px" width="400px" >
    <caption class="readHide">기본 정보</caption>
    <tr>
        <td style="background:#ebebeb;">
            발송영업소
        </td>
        <td style="background:#fbfbfb;">
            <?php
            echo $match[1][$branch_start];
            ?>
        </td>
        <td style="background:#ebebeb;">

            도착영업소

        </td>
        <td style="background:#fbfbfb;">
            <?php
            echo $match[1][$branch_end];
            ?>
        </td>
    </tr>
    <tr>
        <td style="background:#ebebeb;">
            보낸분
        </td>
        <td style="background:#fbfbfb;">
            <?php
            echo $match[1][$sender];
            ?>
        </td>
        <td style="background:#ebebeb;">
            받는분
        </td>
        <td style="background:#fbfbfb;">
            <?php
            echo $match[1][$reciever];
            ?>
        </td>
    </tr>
    <tr>
        <td style="background:#ebebeb;">
            품명
        </td>
        <td style="background:#fbfbfb;">
            <?php
            echo $match[1][$prod];
            ?>
        </td>
        <td style="background:#ebebeb;">
            수량
        </td>
        <td style="background:#fbfbfb;">
            <?php
            echo $product_count[1][0];
            ?>
        </td>
    </tr>
    <tr>
        <td style="background:#ebebeb;">
            운송장번호
        </td>
        <td colspan="3" style="background:#fbfbfb;">
            <?php
            echo $match[1][$item_srl];
            ?>
        </td>
    </tr>
</table>


<table cellpadding="3px" width="400px">
    <caption class="readHide">발송추적 정보</caption>
    <thead>
    <tr style="background:#ebebeb;">
        <th scope="col" class="no">날짜</th>
        <th scope="col" class="title">처리점소</th>
        <th scope="col" class="author">연락처</th>
        <th scope="col" class="date">처리현황</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $devided_number = ( $list_count - '7' ) / '4';

    if($devided_number == 0) {
        echo '배송준비중입니다.';
    } else {
        $i = '1';
        while($i < 4)
        {
            $row_list = $i * 4;


            $reg_date = $row_list - '3';
            $stat = $row_list - '2';
            $location = $row_list - '1';
            $tel = $row_list;

            $i++;
            ?>
            <tr style="background:#fbfbfb;">
                <td class="no"><?php echo $match[1][$reg_date];?></td>
                <td class="title">
                    <?php echo $match[1][$location];?>
                </td>
                <td class="author"><?php echo $match[1][$tel];?></td>
                <td class="date"><?php echo $match[1][$stat];?></td>
            </tr>
            <?php
        }
    }
    ?>
    </tbody>
</table>


</body>
</html>
`

**Comment by bjrambo** [comment]
https://github.com/bjrambo/nurigo/commit/2707d976e4c5e0a16ddd867c3814b20e69c5bd5b
누리고에서 제공하는 기능은 여기까지입니다.

사용자 한명만 사용하는 솔루션이 아니기에 다른 택배사의 의한 추가 기능을 마음대로 추가할 수 없습니다. 죄송합니다.
