### ISSUE TITLE
배송비 오류 

### ISSUE THREAD

**Issue by mothercat** [bjrambo/nurigo#209]
![11](https://user-images.githubusercontent.com/16897020/29747359-d014fab4-8b33-11e7-81a7-a254ae3e9d71.JPG)

현재 장바구니에서 배송비무료기준 5만원을 입력해놓은 상태입니다.
사료의 경우 무료배송이 체크되어있는데, 
위의 사진처럼 전체가 5만원을 넘지 않았는데도 무료배송으로 된 상태입니다.

위 케이스 경우, 사료는 무료배송이지만
배송비가 있는 다른 제품 기준으로 5만원이 넘을 시 
무료배송이 되어야 하지만..

5만원이 넘지 않아도 사료의 무료배송때문에 전체가 다 무료배송이 된 상태입니다.

**Comment by bjrambo** [comment]
Fix 81cbdf70707e6465f84bb5922b75bfcb9b5ce013 
배송비 설정에서 마지막에 있는 무료배송비 조건을 잘읽어보시고 해당 옵션을 조절하여 사용하시길 바랍니다.
