### ISSUE TITLE
배송비 오류 2

### ISSUE THREAD

**Issue by mothercat** [bjrambo/nurigo#210]
![33](https://user-images.githubusercontent.com/16897020/29747395-199e65a2-8b35-11e7-9d0e-328b1bb50ee1.JPG)

출력항목에서 배송비를 넣은 후, 

![44](https://user-images.githubusercontent.com/16897020/29747397-2474e654-8b35-11e7-91c9-76afaa88550d.JPG)
무료가 체크되어있는 항목에서는 무료배송 정상적으로 출력

![55](https://user-images.githubusercontent.com/16897020/29747398-2aaafefa-8b35-11e7-83e9-816125b7cb8e.JPG)
무료가 체크되어있지 않은 항목에서는 
배송비가 출력되지 않습니다 !

리스트 출력과 상세페이지 출력 둘다 동일하게 그렇습니다~~

**Comment by bjrambo** [comment]
Fix 30f0e39bab1a9eaef6e8426d9e26edcbace46f17

**Comment by bjrambo** [comment]
Fix 776f1957bfacb9bc1334ad3cf40c0445ec9e23f0
