### ISSUE TITLE
입금완료시 마일리지 지급 or 자동 구매완료 방법좀 안내부탁드립니다.

### ISSUE THREAD

**Issue by imyouridea** [bjrambo/nurigo#212]
안녕하세요. 

포인트 결제 모듈을 찾다가 없어서 누리고로 대신 사용하고있습니다. 
입금완료시 관리자가 수동으로 구매완료를 해줘야 마일리지가 지급되는데요

이걸 입금완료시 마일리지가 지급되게 하거나, 자동으로 구매완료 되게 할수있을까요?
혹은 구매자가 마이페이지에서 구매완료를 할수있게 할수있을까요?

1. 입금완료시 마일리지가 지급되게 하기 
2. 입금완료시 자동으로 구매완료 되게 하기 
3. 구매자가 마이페이지나 타페이지에서 구매완료를 할 수 있게 하기 

위의 세개 중에 하나만 되도됩니다 ㅠㅠ 부탁드립니다.

**Comment by bjrambo** [comment]
말씀해주신 3가지 방법이 보안상과 취약점이 될 수 있는 여건이 있고, 누리고 쇼핑몰의 특성상 한 사이트만을 위한 쇼핑몰 솔루션이 아니기때문에 적용하기가 어렵습니다.

죄송합니다.

**Comment by imyouridea** [comment]
아 여기는 쇼핑몰 다음버전을 위한 의견 접수 같은건가보네요; 저는 제 사이트에 문제를 해결하기위해 문의 드린건데... 잘못왔나보니다. 죄송합니다.

**Comment by bjrambo** [comment]
넵 여긴 누리고쇼핑몰의 솔루션 개발을 위한 공간입니다 :)

**Comment by imyouridea** [comment]
넵 답변 감사합니다. 혹시 

1. 입금완료시 마일리지가 지급되게 하기

를 위해서 어디를 수정해야되는지만 안내받을수있을까요?
어디어디 폴더의 어디어디 문서를 수정하면 된다. 정도만 안내받아도 혼자 처리할수있을듯한데요...

부탁드립니다.

**Comment by bjrambo** [comment]
modules/nstore/nstore.controller.php 파일에서 처리되는것 같습니다.

**Comment by imyouridea** [comment]
안내주셔서 감사합니다. 
제가 사용하는 모듈은 	
nstore_digital/ 였고, 
nstore_digital / nstore_digital.class.php 에서 

const ORDER_STATE_COMPLETE = '2';

주문 완료값을 3에서 2로 변경하여 안내해주신 
modules/nstore/nstore.controller.php 과 같은 기능을 담당하는 
nstore_digital.controller.php 문서에서 2를 완료로 인식하여 결제와 동시에 
마일리지가 지급되었습니다. 

덕분에 많은 도움이 되었습니다. 다만 이렇게 처리하는것이
보안에 취약할수있을까 여쭤봅니다.

**Comment by bjrambo** [comment]
취약점이 심할 수 있습니다.

예를들어 결제이후 결제에 대한 액션을 다시 한번 취소가 가능한경우 취소로 인해 포인트를 되 깍아야 하지만 안깍인다던가..하면.. 오히려 손해만 나오니깐요..ㅎㅎ
