### ISSUE TITLE
누리고 결제 에러

### ISSUE THREAD

**Issue by sarix123** [bjrambo/nurigo#216]
누리고 쇼핑몰 이용하고있습니다. 

바로구매 클릭하거나 장바구니 클릭하여 결제하기 클릭하면 

Fatal error: Call to a member function get Config() on non-object in /home/smho81/www/xe/modules/ncart.view.php on line 303

이렇게 에러가 뜹니다.

해결어떻게해야되나요?

**Comment by bjrambo** [comment]
couponsms 모듈이 설치 되어있지 않습니다
couponsms모듈을 설치 해보세요.

**Comment by bjrambo** [comment]
https://github.com/bjrambo/nurigo/tree/master/modules/couponsms 해당 깃에 함께 배포되는 모듈입니다.
