### ISSUE TITLE
누리고 쇼핑몰에서 컨텐츠몰로 상품등록을 하였습니다

### ISSUE THREAD

**Issue by fy5914** [bjrambo/nurigo#222]
이어서 쇼핑몰 관리자 -> 장바구니 -> cart페이지 관리 -> 결제폼관리에서
  
휴대폰 번호 , 하고 싶은 말씀과 같은 폼을 추가해줬습니다.
 
 
 
문제는 주문결제시에 휴대폰 번호 , 하고 싶은 말씀을 기재해서 결제를 진행해도
 
콘텐츠몰 -> 판매관리 -> 주문상세내역 상에서 전혀 표기가 되지 않고 있습니다.
 
 
 
혹시나 해서, 컨텐츠몰이 아닌 쇼핑몰 일반상품으로 등록을 하고서
 
동일하게, 결제를 진행해봤더니
 
쇼핑몰 -> 주문관리 -> 주문상세내역 에는 표기가 되더군요.
 
 
 
누리고의 자체 문제인 것 같은데, 이곳에 남기면 될런지요..

**Comment by bjrambo** [comment]
Fixed 646ee87

**Comment by fy5914** [comment]
반영해주셨네요 정말 감사드립니다^^
