### ISSUE TITLE
상품분류가 안됩니다

### ISSUE THREAD

**Issue by calvinsnax** [bjrambo/nurigo#225]
https://github.com/bjrambo/nurigo/issues/87

위 링크의 이슈가 동일합니다.
누리고 2.6.2 / 라이믹스 1.9.2 버전입니다.

상품분류에 잘못된 요청입니다. 라는 문구가 표시되고, 분류를 추가하려고 하면 다음과 같은 에러 메시지가 표시됩니다.

msg_parent_node_not_found

**Comment by bjrambo** [comment]
동일한 이슈는 다시열지 말아주세요. 이슈 관리를 위한 방침입니다. 이이슈는 닫고 #87에서 진행하도록 하겠습니다.
