### ISSUE TITLE
상품 분류가 작동하지 않습니다.

### ISSUE THREAD

**Issue by calvinsnax** [bjrambo/nurigo#226]
이슈 올렸었는데 글이 안올라와서 다시 올립니다.

https://github.com/bjrambo/nurigo/issues/87

위 이슈와 동일한 증상입니다.

누리고 모듈 2.6.2 / 라이믹스 1.9.2

상품분류에서 잘못된 요청입니다. 라는 문구가 표시되고 분류를 추가하려고 하면 아래와 같은 에러 메시지를 출력합니다.

msg_parent_node_not_found

**Comment by bjrambo** [comment]
동일한 이슈는 두개 이상 유지하지 않습니다. 그래서 닫아서 목록에 없는 것이니 다시 올리지 않으시길 바랍니다.
