### ISSUE TITLE
-

### ISSUE THREAD

**Issue by bjrambo** [bjrambo/nurigo#24]
-

**Comment by bjrambo** [comment]
처리완료 (don't push origin)

**Comment by bjrambo** [comment]
fixed in https://github.com/bjrambo/nurigo/commit/4e44472f52c7b81466a14017e3b1097b200f1ab1

**Comment by bazakorea** [comment]
안녕하세요.

여기 장바구니 담기는 부분 알려주시면 좋겠습니다.

담긴다는 메시지는 뜨는데 가보면 않보입니다.

개별로 담는 건 잘 됩니다.

https://www.xpressengine.com/index.php?mid=qna&search_target=title_content&search_keyword=%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88&document_srl=23076281

**Comment by bjrambo** [comment]
@bazakorea 이슈검토하고 문제확인하는데 몇일 소요될 수 있습니다.
그리고.. 제가 이 프로젝트만 하는게 아닌지라 바로바로 답변이 어려울때도 있어요.

조금 기다려주세요. 곧 배포일이기때문에 배포준비해서 도움을 드릴 수 있도록 할께요..

**Comment by bazakorea** [comment]
paypal 연동을 진행 했는데요. 잘 됩니다. 그런데 1,000불 이상 넘어가면 이 메시지가 뜨네요. 

 Price is not a valid numeric value

원화로 바꿔서 하면 120만원이 넘어가면 그러네요. 페이팔에서 금액을 제한 하기도 하나요?
아니면 xe에서 수정해야 하는지요? 바쁘시겠지만 보시면 답변 부탁드립니다.
