### ISSUE TITLE
상품등록 및 수정시 오류

### ISSUE THREAD

**Issue by treasurej** [bjrambo/nurigo#26]
상품등록 및 수정시 오류
![dberror](https://cloud.githubusercontent.com/assets/4101147/13432013/2adfe566-e00f-11e5-93aa-5fc9b4bca11d.png)

**Comment by bjrambo** [comment]
안녕하세요.
버그 수정하는데 어디 모듈인지 알려주신다면 조금 원활하게 수정가능할것 같아요 :) 
워낙 많은 모듈이 함꼐 공존해서 ㅠ.ㅠ  일딴 해당 버그는 확인해보겠습니다.

**Comment by treasurej** [comment]
상품모듈입니다. nproduct

**Comment by bjrambo** [comment]
@treasurej 해당 모듈에서 상품을 등록 해봣는데 문제점이 일어나지 않았습니다.
테스트하신 환경이 어떤 환경이시며, 문제가 되는 서버알려주신다면 제가 확인해볼께요..

**Comment by treasurej** [comment]
최근에 사용자 두 분이 에러가 나고 있는데
XE코어 1.8.17에 csrf 반영
누리고 최근 0.2beta

한 분은
PHP 5.5
마리아DB

files 퍼미션 문제도 관련이 있는지 확인 부탁드립니다.

**Comment by bjrambo** [comment]
@treasurej 내일 저녁까지 한번 테스트 해보고, 문제 확인되면 고쳐보도록 하겠습니다..

**Comment by eondcom** [comment]
1364 [sqlstate] 로 구글링 해봤는데
http://stackoverflow.com/questions/5000547/error-1364-hy000-field-my-date-doesnt-have-a-default-value

**Comment by eondcom** [comment]
xe 설치할 때 db 종류에 따른 오류 같아 보이긴 하는데.. 음

**Comment by eondcom** [comment]
mysqli 일 경우는 저런 오류가 나타나고,
mysql 로 할 경우는
Field 'value' doesn't have a default value
이런 오류가 나네요.
음.. 설정 문제인거 같기도 한데..

**Comment by eondcom** [comment]
[mysql] Field 'name' doesn't have a default value 에러 해결… 이라는 글인데요,
출처 : http://dryad.kr/bbs/board.php?bo_table=rboard01&wr_id=292

여러가지를 검색해본 결과 직접적으로 문제가 발생하는 부분에서 업데이트를 시켜주라는 글밖에 없음.
웹서버를 운영하는 업체에서 하나하나 다 업데이트를 시킬수 없음... 그게 몇개인데 혹시나 서버에서 설정할수 있는 부분이 있지 않을까 고민중에... 발견!!
 
 
﻿이 문제는 필드의 기본값이 설정되어 있지 않아서 나오는 문제입니다.

MySQL 4.x 에서는 이런문제가 발생하지 않는데 MySQL 5.x 에서는 이런문제가 발생합니다.
보통 phpMyAdmin 이런것으로 DB 를 관리하실텐데요.

필드를 만들때 not null 로 설정시 default 값에 아무것도 입력하지 않을경우 자동으로 '' 이렇게 셋팅이 안됩니다.
그래서 insert 쿼리 할때 default 값이 없는 필드를 그냥 무시하고 넘길때 아래처럼 에러가 발생하는겁니다.
 
Field 'name' doesn't have a default value
 
뭐 정확하게 필드마다 값을 지정해주는것도 좋겠지만 특별히 지정 안해줘도 되는 부분에 '' 이걸 다 셋팅해주긴 귀찮고 not null 을 null 로 하긴 싫고.....
my.ini 셋팅값을 변경하면 문제는 해결됩니다. 아래의 부분을 # 으로 주석처리해주세요

sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
그러면 문제해결됩니다.
 
 
cenots 5.7 기준으로 소스로 기본 설치한 서버라면
 
/etc/my.cnf
vi /usr/local/mysql/my.cnf
 
가 존재할것임..
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES << 입부분에 # 주석처리 후
재시작
 
/etc/init.d/mysqld restart

**Comment by eondcom** [comment]
php 5.6.18 기존 사용 중이던 누리고 - 오류 없음.
php 5.6.7 새로 설치한 누리고 - 오류 있음.

php 문제나 누리고 자체의 문제라기 보다 일단 DB에서 해당 컬럼에 값이 없어서 그런거 같은데..

저 같은 경우는 xe_nproduct_extra_vars 에서 오류가 나길래. 없음을 null 로 변경해주니 오류가 사라졌어요.

![20160302](https://cloud.githubusercontent.com/assets/3683813/13446708/0b9f6bc8-e059-11e5-908d-4a71025b62d5.png)

**Comment by eondcom** [comment]
디비 해당 컬럼 종류가 설정이 안되어있어서 그랬는데, 지속적으로 관리가 안되다보니깐 XE 최신버전과 호환 때문에 그랬던거 같아요. 예전 xe 버전에서 사용할 땐 이런 문제가 없었는데 최신 버전으로 설치할 경우에 발생하는 문제 같기도 하네요?;

**Comment by eondcom** [comment]
근데 기존에 사용하던 제 계정에서는 굳이 저렇게 수정 안해줘도 오류는 발생하지 않았어요. (__);

**Comment by eondcom** [comment]
상품등록은 저렇게 해결했는데, 메인등록시 이런 오류가 또 나타나네요. 

Prepared statement failed: INSERT INTO `xe_nproduct_display_items` (`category_srl`, `module_srl`, `item_srl`, `node_route`, `regdate`) VALUES (?, ?, ?, ?, ?)Field 'list_order' doesn't have a default value Array ( [0] =&gt; mysqli_stmt Object ( [affected_rows] =&gt; -1 [insert_id] =&gt; 0 [num_rows] =&gt; 0 [param_count] =&gt; 5 [field_count] =&gt; 0 [errno] =&gt; 1364 [error] =&gt; Field 'list_order' doesn't have a default value [error_list] =&gt; Array ( [0] =&gt; Array ( [errno] =&gt; 1364 [sqlstate] =&gt; HY000 [error] =&gt; Field 'list_order' doesn't have a default value ) ) [sqlstate] =&gt; HY000 [id] =&gt; 5 ) [1] =&gt; iiiss [2] =&gt; 202 [3] =&gt; 156 [4] =&gt; 163 [5] =&gt; . [6] =&gt; 20160302100141 )

**Comment by eondcom** [comment]
Data truncated for column 'list_order' at row 1
http://hongpage.co.kr/post/366

list_order가 또 안맞아서 메인진열에서 문제가 발생하네요.

**Comment by eondcom** [comment]
![20160302-2](https://cloud.githubusercontent.com/assets/3683813/13447690/cbe07934-e060-11e5-9b58-d4640e072ce8.png)

이건 list_order을 null로 하면 안되고 0으로 해야하는데 설정하니 위와 같은 오류가 발생해서
처음에는 a_i 에 체크해서 진행하니 정상적으로 메인 진열 되네요.
이후부터는 a_i 체크해제해도 정상적으로 메인 진열 되구요;;

**Comment by bjrambo** [comment]
오류발생한 서버 혹시 제공 해주실 수 잇으신가요?

**Comment by bjrambo** [comment]
이 문제는 서버 세팅에 문제인것 같습니다.

각 회사의 DB사용에 따라 mysql버전이나 mariadb의 버전에 따라 달라지는 세팅으로 보여집니다.

이사항은 좀 더 지켜보고 고쳐볼 필요가 잇을 것 같아요.

**Comment by qnag604ko** [comment]
맨위 오류발생한 이미지 주인입니다.
예전에 해결되서 잠깐보류하다 다시와서 시도해보니 같은오류가 있습니다.

오류가 있던 시스템 : Apache 2.4.10  /  PHP 5.6.0  /  MySQL 5.7 또는 MariaDB 각종 버전

현재 해결된 시스템 : Apache 2.4.6  /  PHP 5.5.3  /  MySQL 5.6.13
이 시스템으로 사용 시 현재는 아무런 에러가 없습니다.
