### ISSUE TITLE
\modules\inipaystandard\inipaystandard.class.php:100 발생

### ISSUE THREAD

**Issue by juhyeoncho** [bjrambo/nurigo#270]
결제가 취소되었습니다. (로그인 안 풀림)
\modules\inipaystandard\inipaystandard.class.php:100

잘못된 요청입니다. (이땐 로그인 풀림)
\modules\inipaystandard\inipaystandard.class.php:100

로그인이 풀리기도 하고 안 풀리기도 합니다

**Comment by treasurej** [comment]
라이믹스 관리자 페이지 - 시스템 설정 - 보안설정

- SameSite 속성 사용 "None"
- SSL 전용 세션 사용 "예"

이렇게 두 설정을 하신다음
- "캐시파일 재생성"
- 브라우저의 쿠키값 모두 삭제 (그냥 F5나 Ctrl_F5로 새로고침 하면 안됨.)

그다음 결제 테스트 해보세요~^^
꼭 라이믹스 버전이어야 하고,
라이믹스가 아닌 경우 관련 소스코드를 추가해야 합니다. (작업의뢰 등)
