### ISSUE TITLE
상품관리에 버그로 보입니다.

### ISSUE THREAD

**Issue by choi6157** [bjrambo/nurigo#30]
수고하십니다. ^^
원인을 찾느라 재설치 점검 반복으로 하루가 획 지나갔습니다. ㅜㅡ

페이지 관리 > 추가등록폼 관리에서 ..

badge
상품아이콘
다중선택(checkbox)
new
best
hot
sale 

했는데 등록이 안되고 다시 초기화 되는 현상입니다.
상품기본정보 아래 상품아이콘 체크박스 생성 안되며 해당 사용자 페이지는 액박현상이 생깁니다.
다시 이전버전으로 돌아가면 정상 작동됩니다.
체크 부탁드립니다.

**Comment by bjrambo** [comment]
@choi6157 혹시 어떤경로를 통해서 접근하셧는지 이미지로 알려주시면 좋을 것같아요.

**Comment by choi6157** [comment]
![admin](https://cloud.githubusercontent.com/assets/12145610/13737647/34254326-ea02-11e5-8be9-96ca1d1dffff.jpg)
