### ISSUE TITLE
네이버페이 제작의뢰드립니다.

### ISSUE THREAD

**Issue by garnecia** [bjrambo/nurigo#31]
전체공개했으면 좋겠습니다.

금액이 어느정도 될까요 ? ㅎㅎㅎㅎ

garnecia@gmail.com 

으로 연락주셔도 됩니다.

**Comment by bjrambo** [comment]
네이버 페이 문의결과, 네이버 페이를 이용한 자체 솔루션으로는 개발이 불가능할것 같아요..

지원에 대한 api도 재대로 지원안되어있고, 공용 누리고 모듈으로써 바로 모듈 만들어드리기엔 조금 힘들어보이는 형태이더군요.

(네이버 페이를 하기위해서 승낙을 받아야 그 이후 개발에 필요한 자료를 구할 수 잇는 상황)

**Comment by garnecia** [comment]
제가 이미 신청을 해서 자료는 다 갖고있습니다

제가 본 바로는 이 자료면 충분히 가능할거같은데요

자료 넘겨드리는 걸로 처리가될런지요

2016년 3월 26일 토요일, BJRambo<notifications@github.com>님이 작성한 메시지:

**Comment by bjrambo** [comment]
@garnecia 제 네이버 메일로 알려주시면 한번 확인해볼께요~ 기간은 좀 걸릴지도 몰라요..ㅠㅠ

**Comment by garnecia** [comment]
개인정보 문제도 있고 애매해서, 그냥 혼자 근근이 개발해보도록 하겠습니다.

모르는 부분은 질문드려도 될까요 ㅎㅎ
