### ISSUE TITLE
PHP7에서 500에러

### ISSUE THREAD

**Issue by treasurej** [bjrambo/nurigo#33]
최근 PHP7에서 누리고 관리자 메뉴에서 각 모듈(상품관리/결제관리/마일리지/카트설정/통화설정 등)에 접근하면 500에러가 뜨더라구요~
호스팅은 카페24이구요,
PHP5로 바꾸니까 그제서야 잘 되더라구요~

**Comment by bjrambo** [comment]
PHP에서 처리하는 정규식에 대한 용량이 있는데 그 용량이 초과하게 되면 문제 생길수도 있다는 사실도 어느정도 받은바 있습니다 확인해보겠습니다.

**Comment by bjrambo** [comment]
php7에서는 오브젝트로 사용된 `$this`가 재대로 불러오지 못한 경우인것 같습니다.

각 모듈에서 $this 정보를 보내 해당 모듈의 정보를 불러오도록 했습니다. 

그래서 정상 작동까지 확인을 해봤어요.

같은 cafe24호스팅 신청하고 php7으로 설치하고, error디스플레이 띄우도록 호스팅사에 전화로 처리해달라고 하고, 처리했습니다 :)

한번 확인해보세요

**Comment by YongilChoi** [comment]
I met same error when I install some plugin. 

I can not solve it. 

I am using this version :  PHP7.0.0p1 on cafe24 hosting service provider. 

I have
