### ISSUE TITLE
이니시스 웹표준 결제모듈 문자 발송문제

### ISSUE THREAD

**Issue by imadonis** [bjrambo/nurigo#37]
누리고 쇼핑몰로 쇼핑몰을 구축하고 있습니다.
 
패치를 다하고 전자결제 이니시스 웹표준 결제모듈로 epay 설정을 하였습니다.
 
그런데  payntoy  문자메세지 오지 않습니다.
 
이니시스 에스크로 5  플러그 인을 설정하면 되는데 
 
모듈방식으로 epay 설정하면 문자 메세지가 오지 않네요 !!!
 
한번 검토 해주세요 ...!!!!

**Comment by bjrambo** [comment]
![_103016_053807_pm](https://cloud.githubusercontent.com/assets/4381756/19835366/9fa17d2a-9ec7-11e6-8a0c-ee7d07dc937b.jpg)
최신버전에서 정상적으로 문자 발송되는 것을 확인했습니다.

(최신버전에서 친구톡 발송이 가능하기 때문에 친구톡으로 온 문자 메세지입니다.
