### ISSUE TITLE
상품 백업기능 추가건의

### ISSUE THREAD

**Issue by blog119** [bjrambo/nurigo#40]
SQL을 잘 알지 못하는 상태에서.. 상품을 수십~수백개를 올려놓으니 늘 불안합니다.

<상품관리>에서 <페이지>별로 백업기능이 있었으면 좋겠습니다

PS. 이때 작업의 편의를 위해서,

1) <페이지>별로 아니고 <상품관리> 통쨰로 백업(download)/복원(upload)

혹은

2) 타 DB용도 가능한 범용 백업이 아닌 오직 <누리고> 에서만 백업/복원 이 가능한 파일

이라도 일단은 꽤나 안심이 될거 같습니다.

**Comment by bjrambo** [comment]
누리고에서 해당 기능을 제공해드리면 정말 정말 좋지만,
이 부분의 대해서는 전적으로 사용자에 따라 상품의 대한 내역이 모두 지워지거나 복구불가능한 부분이 생길 수 있는 부분이 있습니다.

그렇기 때문에 자체적으로 SSH으로 운영하시는 XE사이트를 전체적으로 data및 DB를 백업하는 방법을 사용하시는걸 권고하는 편입니다.

누리고에서 제공을 해주면 좋겠으나, 오작동으로 인한 부분을 전체적으로 책임지고 제공할 수 없다고 판단되는 부분이라, 제공하지 않도록 하는것이 좋겠다는 판단이 들었어요..

죄송하지만.. 앞서 말씀드린것처럼 전체적으로 정기적으로 항상 SSH내에서 사이트 전체를 백업하는 방향으로 생각해보시길 권장합니다.(_ _ )

원하시는 답변이 되지 못해서 죄송합니다.
