### ISSUE TITLE
결제완료 트리거 관련 문의입니다.

### ISSUE THREAD

**Issue by ubfspringx** [bjrambo/nurigo#41]
람보님 늘 수고가 많으십니다. 앱개발자 단희아빠입니다.

결제완료시 푸시 알림 작동하려고 작업중인데... 결제완료시 트리거를 받으려고 보니 두개가 있더라구요...

epay.controller.php에서 

226번째 $output = ModuleHandler::triggerCall('epay.processPayment', 'after', $args);

476번째 $output = ModuleHandler::triggerCall('epay.processPayment', 'after', $args);

이 두개가 어떤 차이가 있는지 궁금합니다. 

그리고 paynoty모듈에서

paynoty.controller.php에서 

185번째 줄 $obj->document_srl이 나오는데, 위의 두 트리거 $arg에서는 document_srl이 보이지 않아서, $obj->document_srl 이 값을 그대로 써도 될지 문의드립니다.

**Comment by bjrambo** [comment]
processPayment 함수에서 넘기는 `$args`값에서 넘어가는 `document_srl`이 없다면, 쓰지 않아도 됩니다. 다만, 링크연결을 위한 각 상품의 고유 값이 넘어간다면 그곳으로 연결시켜줘야겠죠...

epay에 중복된 트리거가 함께 작동되고 잇었던것 같은데, 아마도 제작자 입장에서는 `before` `after`구분을 위한 항목이였나봅니다. 수정해두겠습니다.

**Comment by bjrambo** [comment]
https://github.com/bjrambo/nurigo/commit/dbeefb0124977e0bc0e2984adf88ac1494a83cc7
비포 에프터 이슈는 아닌것 같고, 다른 누리고 모듈과 정리가 안될듯 하여 각 트리거에 넘어가는 정보중에 `review_order` 라는 정보를 만들었고, `procEpayReviewOrder`메소드에서는 
```php
$args->review_order = true;
```
`procEpayDoPayment`메소드에서 실행된 트리거는 
```php
$obj->review_order = false;
```
으로 반환하도록 수정해드렸습니다.

구분이 필요할시 이 변수를 사용하면 될것 같아요.
```php
if($obj->review_order === true)
{
$review = 'foo';
}
```

이렇게요 :)

**Comment by bjrambo** [comment]
`paynoty.controller.php` 파일내에 185번째줄이 없;;

**Comment by ubfspringx** [comment]
아... 84번째 줄입니다. ...ㅜ,.ㅜ

**Comment by bjrambo** [comment]
`triggerCompletePayment` 메소드에서 해당 트리거 실행시, `$state`를 디버그 한 정보 있으시면 남겨주세요.

**Comment by ubfspringx** [comment]
네 확인해보고 알려드릴께요. 감사합니다. ^^

**Comment by ubfspringx** [comment]
결제완료시 트리거에서 받은 $state 변수 json_ecode한 내용입니다.

{"xe_mid":"NJCart","target_module":"ncart","transaction_srl":8825,"epay_module_srl":"2148","module_srl":"2151","plugin_srl":2146,"order_srl":8823,"order_title":"\uad6d\uc0b0 \ucd5c\uace0\uae09\ubb3c\ud478\ub808(\uba85\ud488)37P","payment_method":"BT","payment_amount":"400000","p_member_srl":1,"p_user_id":"kkulbam","p_name":"\uc63b\uce60\uc7c1\uc774","p_email_address":"namwonjeki@linuking.com","result_code":"0","result_message":"success","pg_tid":"20160504212932024881128813","state":"1","extra_vars":{"result_code":"0","result_message":"success","pg_tid":"20160504212932024881128813","vact_bankname":"\uad6d\ubbfc\uc740\ud589","vact_num":"506-22-0437-523","vact_name":"\uac15\uc2e0\uc11d","vact_inputname":"\uac15\uc2e0\uc11d"},"return_url":"\/MGMall\/index.php?act=dispNcartOrderComplete&order_srl=8823&mid=NJCart"}

제가 궁금한 것은 이 state 변수 안에 해당 제품의 고유 item_srl을 어떻게 알 수 있을까 하는 것입니다.
transaction_srl은 결제하는 고유번호같고, order_srl은 해당제품과 관련된 것 같은데, 예를 들어서 위의 예를 들면 http://domain.com/8823 이렇게 하면 해당 제품페이지로 갈 수 있는 것인가요?

**Comment by bjrambo** [comment]
누리고에서 등록하는 항목이 Document인것으로 보여집니다.

만일 document 를 사용하여 상품을 입력하는것이라면, XE에서는 document에 맞는 모듈을 출력해줍니다.

ex) 도메인.com/documet_srl -> 도메인.com/goods/document_srl
으로 변환시키는 코드를 `htaccess`에서 처리해주니, 정당하게 말씀하신방법으로 넘겨주시면 될것 같아요.
order_srl이 대부분 상품의 제품의 연결된 srl을 담당하고 있긴합니다만, 좀더 이부분의 대해서는 저도 테스트를 해보고 연락드리는것으로 하겠습니다.

**Comment by ubfspringx** [comment]
감사합니다. ^^

**Comment by bjrambo** [comment]
말씀하신 document_srl 은 누리고에 추가하긴 어려워질것 같네요.

장바구니모듈에서 전혀다른 방식으로 주문번호를 생성하고 넣는 방식입니다.
다른 방법으로 상품정보를 가져오는 방안을 마련해보시기 바랍니다.

대신, obj에서 제목및 일부 정보도 함께 넣을 수 있도록 해드리겠습니다.

**Comment by ubfspringx** [comment]
아 그러면 푸시 알림시 장바구니로 이동하도록 하겠습니다.
