### ISSUE TITLE
상품별 조회수 확인 기능

### ISSUE THREAD

**Issue by dcaps001** [bjrambo/nurigo#43]
쇼핑몰에 전시된 상품별 조회수를 확인할 수 있었으면 좋겠습니다.
쇼핑몰 제품중 어떤 제품군에 관심을 가지고 클릭하는지를 조회수로 보면 어느정도 판단이 가능할 것 같기 때문입니다.

가능하다면 추가했으면 합니다.

**Comment by bjrambo** [comment]
조회수의 경우 필요할 경우인지 의문입니다.

불필요한 정보는 일딴 제외할 예정이에요. (일부사이트에서 조회수를 사용하는경우로 판단됩니다.) 좀 더 많은 쇼핑몰 솔루션에서 사용에 용의한 편으로 보이면 추후 지원해보도록 하겠습니다. (_ _ )
