### ISSUE TITLE
주문시 주문자에게 멜 발송 기능

### ISSUE THREAD

**Issue by linuking** [bjrambo/nurigo#49]
현재 누리고에서는
상품을 주문했을 경우 관리자에게만 멜 발송이 되고
주문한 소비자에게는 주문서 멜 발송이 이뤄지지 않고 있습니다.
주문자에게 주문서 내역이 메일로 발송될 수 있도록 가능할까요.
감사합니다.
행복한 하루 보내세요.

**Comment by bjrambo** [comment]
메일발송에 대한 XE에서 정확한 방법은 라이믹스를 사용하여 고급메일기능이랑 우리메일이랑 연동하거나, 아니면 XE에서 우리알림모듈+고급메일발송모듈(xe용)으로 구현하시는게 좋을것 같아요.
