### ISSUE TITLE
누리고 쇼핑몰 warning 메시지

### ISSUE THREAD

**Issue by bleu1115** [bjrambo/nurigo#50]
Warning: Creating default object from empty value in /free/home/bleu1115/html/modules/ncart/ncart.model.php on line 30

http://wefont.co.kr/index.php?mid=font_standard&category=873

컨텐츠 쇼핑몰 제작중입니다.
위와 같은 warning이 항상 뜨는데 어떻게 해결해야 될까요?
누리고 1.05버젼을 사용했습니다.

**Comment by bjrambo** [comment]
`/modules/ncart/ncart.model.php`
파일에 config가 초기화 되지 않아서 생기는 문제입니다.
해당파일 27번째줄의 `$config = $oModuleModel->getModuleConfig('ncart');` 코드 아래,

```php
if(!$config)
{
	$config = new stdClass();
}
```
를 추가해보시기 바랍니다.

**Comment by bleu1115** [comment]
답변 감사합니다^^

**Comment by bjrambo** [comment]
fix in
