### ISSUE TITLE
통화 설정에서 .. 

### ISSUE THREAD

**Issue by byunbbhh** [bjrambo/nurigo#51]
통화 설정에서 ..  
태국 바트로 선택이 가능 하게 할수 있을까요 ? 
감사합니다.

**Comment by bjrambo** [comment]
fix in https://github.com/bjrambo/nurigo/commit/4a4622cf0a517a37df5d4bd81241daec515e7fd0 https://github.com/bjrambo/nurigo/commit/86833be20e448d20bb558c73cb8d372d1ddb802e
