### ISSUE TITLE
안녕하세요? 다시 warning 문의 드립니다.

### ISSUE THREAD

**Issue by bleu1115** [bjrambo/nurigo#53]
누리고 활용해서 디지털 콘텐츠 쇼핑몰을 제작중입니다.
http://wefont.co.kr

**첫번째 현상은**
Home > 콘텐츠몰 > 콘텐츠관리 화면 진입시 상단에
Warning: Creating default object from empty value in /free/home/bleu1115/html/modules/nstore_digital_contents/nstore_digital_contents.admin.view.php on line 51
메시지가 뜨며
디지털콘텐츠 목록이 끝까지 나오지 않는 현상이 있습니다.

**두번째 현상은**
cympusadmin 초기화면 상단에 아래와 같은 Warning이 나오는데 안 나오게 할수 없을까요?
Warning: Missing argument 1 for cympusadmin::init(), called in /free/home/bleu1115/html/modules/cympusadmin/cympusadmin.admin.view.php on line 20 and defined in /free/home/bleu1115/html/modules/cympusadmin/cympusadmin.class.php on line 15

도움을 구합니다. 감사합니다.

**Comment by bjrambo** [comment]
두번째현상은 이미패치되었습니다.

**Comment by bleu1115** [comment]
누리고 1.05버젼을 사용중인데 추가로 패치된 내용이 있나요? 어디서 받을수 있는지요

**Comment by bjrambo** [comment]
오늘 정식적으로 패치되어 배포될 예정입니다.
