### ISSUE TITLE
결제모듈 문의 드립니다..

### ISSUE THREAD

**Issue by waaji** [bjrambo/nurigo#55]
결제모듈 플러그인 중에 이니시스에스크로 가 있는데

저희가 네이버 쇼핑에 입점하려고 하는데 에스크로 이용약관 동의화면이 별도로 확인되지 않는다고 

거부 당하네요... 당연히 이니시스에 에스크로 기능 설치 해놨는데도.. 그런상황입니다..

에스크로 플러그인 제대로 동작하고 있는건가요 ㅠ.ㅠ

**Comment by bjrambo** [comment]
이니시스 에스크로으로 정상적인동작을 모두 확인했습니다.

만약 동의 관련 화면이 없다면 별도의 위젯페이지혹은 문서 페이지를 만들어 이니시스 에스크로 이용약권을 명시 해두시고 네이버 측에 문의해보시기 바랍니다.

일전에 XETOWN을 통해서 해당 사이트에 이니시스에스크로 설정이 잘못되어있는것 같았습니다.
정상적인 세팅으로는 그 결제창이 아니라 이시시스 에스크로 따로 설정이 뜨게됩니다.
플러그인 생성부터 차근차근 설정해보시기 바래요
