### ISSUE TITLE
결제하기 버튼 눌렀을때 에러 좀 봐주세요

### ISSUE THREAD

**Issue by bleu1115** [bjrambo/nurigo#56]
Warning: Creating default object from empty value in /free/home/bleu1115/html/modules/ncart/ncart.view.php on line 400

화면 상단에 위와 같은 메시지가 뜹니다.
그 후 결제 진행은 또 문제가 없는데 위의 메시지는 왜 나오는 걸까요?
pg사는 유플러스입니다.

**Comment by bjrambo** [comment]
클래스 초기화가 되어있지 않아서에요.
아직 각각 안된 부분 많은것 같네요~ ㅠ.ㅠ

좀더 살펴보고 고쳐보도록 하겠습니다 제보감사합니다.!
