### ISSUE TITLE
결제 관련 warning 해결이 급합니다

### ISSUE THREAD

**Issue by bleu1115** [bjrambo/nurigo#58]
Warning: Creating default object from empty value in /free/home/bleu1115/html/modules/ncart/ncart.view.php on line 400

앞서 이 내용으로 문의드렸는데요.
제가 지금 카드사 심사를 2/3 정도 통과한 상황인데 곧 사이트를 오픈하게 됩니다.
위와 같은 메시지가 결제시마다 사용자에게 보여지게 되어
사이트의 신뢰도에 문제가 있다고 느낄수 있는 부분인것 같습니다.
복잡하지 않은 부분이라면 제가 직접 수정을 할수 있도록 수정내용을 알려주셨으면 합니다.

**Comment by bjrambo** [comment]
XE나 Rhymix 쓰시면 해당 워닝오류는 전혀 나타나지 않을껀데요?

내일 배포에요. 내일 정상적으로 배포될예정인데,

워닝에러 같은경우 따로 디스플레이 되는 항목이 전혀 없는걸로 보여집니다.

항목이 나타나는 부분이 어떤부분인지 설명해주시고, 혹시 XE버전이 낮은지도 파악하시길 바래요.
(권장사항은 1.8.15 이상입니다.)

**Comment by bleu1115** [comment]
xe사용중이며 누리고는 지난 달 15일 배포된 버젼을 쓰고 있습니다.
정확히 언제 저 메시지가 상단에 표시되나면
장바구니에 물건을 담고 '주문하기' 버튼을 누른 후 입니다.
그후 '결제하기' 누르면 결제화면(엘지 유플러스)가 팝업됩니다.
추측건데 기능은 정상 작동하나 위의 메시지는 계속 나오는 상황입니다.

**Comment by bjrambo** [comment]
메세지가 어떤식으로 뜨는지 스크린샷으로 알려주세요
만일 기존에 설명드린 워닝에러 메세지 처럼 파일속에서 뜨는거면 정식 오픈하셔도 무시하시면 되나, 브라우저에서 뜨는거면 어떻게 뜨는지 확인이 필요해요.

**Comment by bleu1115** [comment]
http://wefont.co.kr/files/wsm/err400.png
화면 좌상단에 뜹니다

**Comment by bjrambo** [comment]
xe/config/config.inc.php 파일에 10번째줄부터

```php
if(version_compare(PHP_VERSION, '5.4.0', '<'))
{
	@error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED ^ E_WARNING);
}
else
{
	@error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED ^ E_WARNING ^ E_STRICT);
}
```
코드랑 동일한지 확인해보시겠어요?

**Comment by bjrambo** [comment]
왜냐하면 XE를 정상적으로 설치해서 쓰고있다면 해당 에러메세지는 절대 드지 않아야 정상인 상황이라서요..

**Comment by bleu1115** [comment]
if(version_compare(PHP_VERSION, '5.4.0', '<'))
{
	@error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED ^ E_WARNING);
}
else
{
	@error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED ^ E_WARNING ^ E_STRICT);
}
위 내용이 제 서버상의 파일 내용으로 동일한 것 같습니다.

**Comment by bjrambo** [comment]
서버 XE설치한 공간에 .htaccess 파일수정하신적있나요? 추가하신 항목이 있다면 알려주세요.

**Comment by bjrambo** [comment]
아 그리고 config.user.inc.php 파일도 존재하는지 확인해주세요
서버내에서 xe/config/config.user.inc.php 경로입니다.

**Comment by bleu1115** [comment]
.htaccess 수정한 적 없구요.
config.user.inc.php도 존재합니다.

혹시 이 경고 메시지와 연관이 있는지도 모르겠는데요
대시보드 장바구니 페이지에서  이와 같은 워닝도 뜹니다.
Warning: Creating default object from empty value in /free/home/bleu1115/html/modules/ncart/ncart.admin.view.php on line 203

http://wefont.co.kr/files/wsm/err203.png

**Comment by bjrambo** [comment]
존재한다는 config.user.inc.php 소스내용 알려주새ㅐ요,

**Comment by bleu1115** [comment]
죄송합니다 
config.inc.php 는 존재하는데 config.user.inc.php 는 해당 폴더에 없습니다.

**Comment by bjrambo** [comment]
@bleu1115 서버 접속가능한 SFTP (SSH접속) 정보와 관리자 계정 알려주세요

**Comment by bleu1115** [comment]
메일 보내드렸습니다. ^^

**Comment by bjrambo** [comment]
서버관리자가 본인이신가요?
서버 관리자에게 php.ini 에 있는 항목들중

display_errors
display_startup_errors
를 off으로 설정해달라고 요청해주세요.

**Comment by bleu1115** [comment]
서버관리는 웹호스팅 업체에 문의드려야 합니다.
위와 같이 php.ini 파일 수정 요청을 드리겠습니다.

**Comment by bleu1115** [comment]
해당사항 요청했으나 불가하다고 합니다. 다른 해결책은 없을까요?
아래는 웹호스팅 업체의 답변입니다.

"단독 호스팅 또는 클라우드 호스팅을 사용을 하신다면 변경을 해 드릴수 있으나 이용하시는 웹호스팅은 여러 고객님이 함께 사용하는 공용 서버이기 때문에 요청 하신 내용을 처리를 해 드리기 어렵습니다. "

**Comment by bjrambo** [comment]
@bleu1115 이전밖에 답이 없습니다
해당 오류 말고도 여러 오류가 있을껀데, 그 항목들 마다 전체적으로 잡아주기 보단 서버 이전으로 깔끔하게 오류를 안뜨게 하는게 더 낫습니다.

안된다고 하면 이전 고려할꺼라고 호스팅사에 알리고 그래도 안된다고 한다면 이전하십시오.

**Comment by bleu1115** [comment]
다시 한번 요청을 해봐야겠네요.
근본적으로 위와 같은 오류가 생기는 이유가 무엇인가요?
그에 대한 해결이 먼저이지 않나 싶습니다.

**Comment by bjrambo** [comment]
@bleu1115 클래스 초기화가 안되어있어서 그렇습니다
$args->member_srl = $member_srl 이라는 소스가 있을경우
$args 에 대해서는 항상 초기화가 되어야 합니다

$args = new stdClass();
$args->member_srl = $member_srl;

이런형태로 추가가 되어야 하기 때문입니다.

근데 이는 원래 XE에 정상적인 호스팅을 사용하면 오류메세지가 전혀 뜨지 않도록 되어있고 개발모드로 접근해야 뜨는 오류들입니다. 이거 디스플레이 뜨는건 서버 설정에서 오류가 있는 항목이기 때문에 호스팅사에서 해결해줘야합니다.

왜 꺼달라고 요청하는지에 대해서 강력하게 문의 남기세요; 그로인해 오류나 신뢰도 같은것이 많이 떨어지는거고, 사용자가 개발자가 아닌데 왜 이 기능이 이렇게 되어있는지 궁금하다는 등등의 어필을 남기고 안되면 이전하세요.

**Comment by bjrambo** [comment]
@kijin 님께서 도움말씀 주셧어요.

제가 언급해드린 `.htaccess` 파일에

```
php_flag display_errors off
php_flag display_startup_errors off
```
위 소스를 추가해보시기 바랍니다.

**Comment by bleu1115** [comment]
말씀하신대로 htaccess 수정을 통해 에러 메시지 나오지 않게 했습니다.
도움에 감사드립니다. ^^

**Comment by bjrambo** [comment]
fixed in 어딘가..(언제고친거지 ㅡ,.ㅡ )
