### ISSUE TITLE
nurigo-1.1.0 설치 후 오류 및 불편사항 올립니다.

### ISSUE THREAD

**Issue by linuking** [bjrambo/nurigo#59]
bjrambo님께 먼저 감사드립니다.
혹, 도움이 될까해서 몇몇 사항에 대하여 올립니다.

오늘 nurigo-1.1.0 받다 설치하고 확인한 결과입니다.

1.  쇼핑몰 주문관리 클릭하여 들어 가면
![1](https://cloud.githubusercontent.com/assets/19444926/16105603/c07d3b40-33c6-11e6-9acd-541cf3bac6ec.jpg)
아래 그림과 같이 나옵니다. 
![2](https://cloud.githubusercontent.com/assets/19444926/16105640/fdab3f12-33c6-11e6-846b-6e5610a399a7.jpg)

2.  상품분류가 아래와 같을 때 상품관리 화면에 분류 리스트가 모두 나오지 않고 일부만 나옵니다.
![1](https://cloud.githubusercontent.com/assets/19444926/16105664/5a1cb104-33c7-11e6-94b2-e9d579cb1c22.jpg)

아래와 같이
![1](https://cloud.githubusercontent.com/assets/19444926/16105671/6c9b5b96-33c7-11e6-8ead-9a33a01e03ee.jpg)

3.  비회원이 주문했을 때 결제관리 화면이 다음과 같습니다.
![1](https://cloud.githubusercontent.com/assets/19444926/16105688/a7170d10-33c7-11e6-8da5-bebfa792bfed.jpg)
아이디: 탈퇴한 회원  이름:   닉네임:     공란입니다.
비회원이 주문한 경우일지라도 주문자의 이름이나 닉네임이라도 보이는게 좋을 듯합니다.

4.  cympusadmin 관리자 화면에서 스킨설정 클리하여 들어가려니 아래와 같이 에러가 뜨네요.
![cympusadmin1](https://cloud.githubusercontent.com/assets/19444926/16105711/1642d462-33c8-11e6-94b9-6707429c1a68.jpg)
![cympusadmin2](https://cloud.githubusercontent.com/assets/19444926/16105714/1d2273b4-33c8-11e6-8f6e-8bd7acf08805.jpg)

위와 같습니다.
이것 저것 꼼꼼하게 다 해보지 못하여 모두 확인 할 수 없었지만 일단 제가 확인한 부분에 대하여 참고하시라고 올려 드립니다.

항상 수고해 주셔서 감사합니다.

행복한 하루 보내세요.

**Comment by bjrambo** [comment]
버그가 있나보군요. 아직 서버환경이 여러곳에서 테스트할 수 있는 환경이 안되어서.

한번 확인해보도록 할께요.

**Comment by linuking** [comment]
저야 뭐~~
님께서 수고하고 노력 해 주시는 거 따복따복 받아 먹기만 하는 처지라 뭐라 드릴 말씀이 없네요.
항상 고맙다는 말 밖에.....
그저 감사하다는 말씀만 드립니다.
건강하세요.

**Comment by bjrambo** [comment]
2번항목의 경우 해당 스킨설정페이지를 제외하겠습니다. (불필요해보여서요.)

필요의 의한 스킨기능을 사용시 따로 설정하여 스킨에서 처리하길 권장합니다.

**Comment by bjrambo** [comment]
fixed in 28b5e54

**Comment by linuking** [comment]
금일 배포한 누리고 1.1.1 에서도
상품관리 화면에 표시되는
상품 분류 나열 표시가 잘리는 현상이 해결되지 않았네요.

**Comment by bjrambo** [comment]
@linuking 이슈를 한이슈에 한가지 문제를 기입해주세요. 이슈 다루기가 어려워져요. 

일딴 fixed으로 된항목은 스킨 제거항목이니, 나머지 문제를 각각 새로 이슈 등록 해주시면 좋을것 같아요.

이슈 문제 번호와 해당 커밋과 일치시키고 해당 문제를 각각 해결되었다는항목으로 정리를 해야하기 때문에 그럽니다 ㅠ.ㅠ

불편하게 해드려서 죄송하지만, 그렇게 해주실 수 있으신가요?
