### ISSUE TITLE
php 7.0.6 업데이트시  결제 관련 다음과 같은 오류가 납니다.

### ISSUE THREAD

**Issue by imadonis** [bjrambo/nurigo#60]
location : ko
package : XE
host : https://4880.net/
app : Microsoft-IIS/10.0
xe_version : 1.8.21
php : 7.0.6
db_type : mysqli_innodb
use_rewrite : Y
use_db_session : Y
use_ssl : optional

php 7.0.6 업데이트시  결제 관련 다음과 같은 오류가 납니다.

무통장입금으로 하였을때  결제완료 화면이 제대로 표현이 안됩니다.

http://4880.net/store_computer/153849

한번 무통장입금으로 결제 해보세요 ...

[22-Jun-2016 20:41:08 Asia/Seoul] PHP Fatal error:  Uncaught Error: Using $this when not in object context in E:\wwwroot\susung\modules\nproduct\nproduct.item.php:85
Stack trace:
#0 E:\wwwroot\susung\classes\template\TemplateHandler.class.php(374) : eval()'d code(73): nproductItem::printPrice(0)
#1 E:\wwwroot\susung\classes\template\TemplateHandler.class.php(374): eval()
#2 E:\wwwroot\susung\classes\template\TemplateHandler.class.php(175): TemplateHandler->_fetch('file://E:/wwwro...')
#3 E:\wwwroot\susung\classes\display\HTMLDisplayHandler.php(61): TemplateHandler->compile('./modules/ncart...', 'ordercomplete.h...')
#4 E:\wwwroot\susung\classes\display\DisplayHandler.class.php(65): HTMLDisplayHandler->toDoc(Object(ncartView))
#5 E:\wwwroot\susung\classes\module\ModuleHandler.class.php(1060): DisplayHandler->printContent(Object(ncartView))
#6 E:\wwwroot\susung\index.php(59): ModuleHandler->displayContent(Object(ncartView))
#7 {main}
  thrown in E:\wwwroot\susung\modules\nproduct\nproduct.item.php on line 85

**Comment by bjrambo** [comment]
안녕하세요 무통장 입금이 플러그인으로 된것을 사용하셧는지 아니면 다른걸 사용하셨는지요?

플러그인형태의 무통장입금에서는 정상적으로 결제가 되었습니다.

**Comment by bjrambo** [comment]
피드백이 없어 이슈 닫습니다.
