### ISSUE TITLE
상품관리에서 분류카테고리가 추가되지 않는 문제

### ISSUE THREAD

**Issue by smg2512** [bjrambo/nurigo#61]
제가 여기 github 파일 올리는 방법을 몰라 링크 합니다. 메인진열 카테고리 추가 등록이 되질 않습니다
설치 파일은 여러번 설치 해봤구요... xe에서 쉬운설치에서는 이러한건 없더라구요.

https://www.xpressengine.com/qna/23162599

**Comment by bjrambo** [comment]
확인해보고 고쳐보도록할께용~

**Comment by smg2512** [comment]
혹시 상품추가 모듈 의뢰 가능한가요? 비용도 같이 말씀해주세요^^


내 삼성 디바이스에서 보냈습니다

-------- 원본 메시지 --------
발신: BJRambo <notifications@github.com> 
날짜: 16/6/28  오후 1:32  (GMT+09:00) 
받은 사람: bjrambo/nurigo <nurigo@noreply.github.com> 
참조: smg2512 <smg2512@naver.com>, Author <author@noreply.github.com> 
제목: Re: [bjrambo/nurigo] 누리고 1.1 버전 설치 후 문제점이 있어서요~ (#61) 

확인해보고 고쳐보도록할께용~

**Comment by smg2512** [comment]
네 감사합니다^^

**Comment by bjrambo** [comment]
fix the 2e549e1
