### ISSUE TITLE
상품주문알림이 작동을 안하는데...

### ISSUE THREAD

**Issue by jeeevely** [bjrambo/nurigo#62]
일단 대상모듈에 어떤걸 넣어야 하는지도 잘 모르겠어요.

보내는 휴대전화 번호: 업체번호
받는 휴대전화 번호: 제 전화번호

이메일주소: 제 메일주소
발신자 정보: 업체명/noreply@업체도메인

문자메세지와 이메일 내용은 수정하지 않고 기존내용 그대로 뒀어요.
1000원 결제테스트 해봤는데 메일도 문자도 안오는데 이거 어떻게 해야 작동이 되는거죠..
메뉴얼이 없으니까 초보자는 정말 하나도 모르겠네요ㅠㅠ
결제모듈은 이니시스 웹표준 결제모듈 사용하고 있습니다.

아래 질문 달아주신 분 글 보니 모듈로 사용하신다고 하시는데 저도 연동모듈로 사용중입니다.
플러그인으로는 이니시스 웹표준결제를 생성할 수가 없어서요ㅠ

**Comment by bjrambo** [comment]
안녕하세요
textmessage모듈을 추가하였는데, 이 모듈은 누리고의 문자메세지api를 발급받으시고 정식적으로 결제하셔야 가능합니다.

혹시, 가입및 테스트를 해보셨는지요?

www.coolsms.co.kr 에서 상품을 구매하시고 api연동이 가능하게 됩니다.

**Comment by jeeevely** [comment]
앗 고객에게 보내는게 아니라 관리자에게 주문알림을 보내는 것을 말씀하시는게 맞나요?

**Comment by bjrambo** [comment]
네 아직 고객에게 보내ㅡㄴ것은 구현이 되어있지 않습니다.

**Comment by jeeevely** [comment]
메일 알람도 별도의 서비스 가입이 필요한건가요?
메일도 마찬가지로 작동이 되지 않아서요.

**Comment by bjrambo** [comment]
@jeeevely 메일알림은 제가 확인해보고 문제파악해보도록할께용~ 그래도 혹시 일부... 메일주소의경우나 스팸매일로 가있는지 파악등등을 함께 확인해주세요.

**Comment by bjrambo** [comment]
@jeeevely 고객에게 보내는것은 아직 구현이 안되어있지만 관리자에게 알림을 보내는 기능은 정상적으로 동작합니다.
설정페이지확인이 필요할 것 같네요.

**Comment by jeeevely** [comment]
확인이 늦었습니다.
관리자에게 보내는 알람 기능 설정을 했으나 메일이 여전히 정상적으로 발송되지 않고 있습니다 (T T

1. 대상모듈: 어떤걸 넣어야하는지 몰라 누리고와 관련된 모듈 모두 넣음
2. 문자+이메일 / 문자메세지 / 이메일 중 이메일 선택
3. 이메일주소: 관리자 메일주소
4. 발신자 정보: 업체명 / noreply@업체도메인
5. 이메일: 기존내용 그대로

사용중인 결제모듈은 이니시스 웹표준 결제모듈과 무통장입금 두가지입니다.

**Comment by bjrambo** [comment]
이니시스웹표준 모듈과, 무통장입금 모듈 두가지도 함께 넣어보세요.

**Comment by jeeevely** [comment]
네 그 두가지도 들어가있습니다.
참고로 웹표준, 무통장 모두 결제모듈의 연동모듈로 지정되어있어요.
누리고 어렵네요ㅠㅠㅠ

**Comment by bjrambo** [comment]
전체적으로 리펙토링 싹했습니다. 오늘 배포본으로 새로 받아보세요.

**Comment by eondcom** [comment]
이거 해당 모듈 외에 따로 설정해야하는 게 있나요?
저도 잘 안되네요;ㅁ;
