### ISSUE TITLE
가상계좌 입금통보, 가상계좌 할당 안되는 문제

### ISSUE THREAD

**Issue by bleu1115** [bjrambo/nurigo#63]
누리고 이용한 컨텐츠 쇼핑몰 운영중에
가상계좌 입금통보, 가상계좌 할당 안되는 문제로 메일 드렸습니다.
찾아보니 아래 분도 동일한 문제를 겪고 계시던데 해결책이 없을까요?
카드결제, 계좌이체는 정상적으로 되는데 가상계좌만 안됩니다.
상세한 내용은 메일 확인 부탁드릴게요.

https://www.xpressengine.com/index.php?mid=qna&search_target=title_content&search_keyword=%EA%B0%80%EC%83%81%EA%B3%84%EC%A2%8C&document_srl=23101727

**Comment by bjrambo** [comment]
https://github.com/conory/rhymix/commit/a519db608dfa8d5b1f6825206836820e64de20ec

혹시 이 파일(XE코어입니다.) 을 수정하시고 테스트해봐주시기 바래요~

**Comment by bleu1115** [comment]
링크 주신대로 3개 파일 수정한 후 테스트했는데 여전히 가상계좌 결제가 되지 않습니다.
위 내용대로 수정한 파일은 다시 원래대로 되돌려 놔야 하나요?
아니면 그냥 유지해도 되는 건가요.

**Comment by bjrambo** [comment]
일딴 유지하셔도 괜찮습니다.

**Comment by bjrambo** [comment]
@bleu1115 일딴 여유를 두고 확인해봐야할 것 같아요 T^T
불편드려서 죄송합니다. 일딴 모듈설정에서 가상계좌여부는 조금 여유롭게 두셔요.

**Comment by bleu1115** [comment]
가상계좌 문제를 말씀드린지 2주가 거의 지나갔네요.
여전히 누리고에서 가상계좌 결제는 전혀 되지 않는 상황입니다.
언제 문제가 해결이 될수 있을까요?

**Comment by bjrambo** [comment]
@bleu1115 혹시 저와 메일을 주고 받으셨던 분이신가요?

일딴 전체적인 서비스를 제가 확인할 수 없어서요.

가능하시면 전반적인 계좌시스템등에 대한 확인을 할 수 있는 정보를 제공해주시는 건 어떠신가요?

(서버 FTP접속, XE관리자 아이디 정보 플러그인 사용여부, PG사의 결제API관련 내용들..

**Comment by bleu1115** [comment]
네 메일 드렸던 사람 맞구요.
서버 관련 정보 및 아이디 지금 메일로 보내드리니 부디 해결이 되면 좋겠습니다.

**Comment by bjrambo** [comment]
46bb468 여기에서 일단 한번 수정해보았는데 이 코드를 이용해서 한번 해보시고, 안되시면 해당 부분의 코드를

` check_csrf="false"`
으로도 변경해서 확인해보시길 권장합니다.

**Comment by bleu1115** [comment]
바꿔주신 코드 부분 수정했으나 이전과 동일하게 정상작동하지 않구요.
아래의 check_csrf 부분은 정확히 어디 넣어야 하는건가요?

**Comment by bjrambo** [comment]
같은자리 추가된코드지우고 check_csrf 항목 위에거 복사해서 넣어보시면되요

**Comment by bleu1115** [comment]
check_csrf="false"
이 항목으로 변경하고 가상계좌결제에 성공했습니다.
테스트가 더 필요할수도 있지만 일단 정상 결제 되는 것으로 보입니다.
어구.. 감사합니다. ㅜㅜ

**Comment by bleu1115** [comment]
상태를 다시 확인해 보니 가상계좌 결제는 진행되어 입금완료 상태로 되지만
결제한 컨텐츠를 다운로드 받으면 입금완료 -> 구매완료로 잠깐 넘어갔다가 
다시 로그인해 보면 입금완료 상태에 머물러 있습니다.
이런 현상이 무한 반복되네요. 입금완료로 자꾸 돌아갑니다.

**Comment by bjrambo** [comment]
@bleu1115 결제완료되었다니 다행이네요. 해당 항목은 다운로드 항목버그인것 같아요! 그부분은 확인해보겠습니다

**Comment by bjrambo** [comment]
@bleu1115 제 사이트에서는 정상적으로 보여지고있는데..
캐시파일 재생성 해보시거나 다른 요인이 없는지 버전을 최신으로 유지하고 계시는지 등등의여부를 확인해주세요

**Comment by bjrambo** [comment]
fixed https://github.com/bjrambo/nurigo/commit/bd5a3fc9f393edd275e0d47302d25216cd6d1ed3

**Comment by bjrambo** [comment]
다운로드 관련 이슈는 새로운 이슈에서 진행해주세요.(한이슈에 하나의 문제나 기능만 입력합니다.)
