### ISSUE TITLE
쇼핑몰 주문관리 화면에 대하여

### ISSUE THREAD

**Issue by linuking** [bjrambo/nurigo#65]
1.  쇼핑몰 주문관리 클릭하여 들어 가면
![1](https://cloud.githubusercontent.com/assets/19444926/16105603/c07d3b40-33c6-11e6-9acd-541cf3bac6ec.jpg)
아래 그림과 같이 나옵니다. 
![2](https://cloud.githubusercontent.com/assets/19444926/16105640/fdab3f12-33c6-11e6-846b-6e5610a399a7.jpg)

**Comment by bjrambo** [comment]
fixed in 5858508
