### ISSUE TITLE
결제관리 화면에서 다음과 같은 불편 사항.

### ISSUE THREAD

**Issue by linuking** [bjrambo/nurigo#67]
3.  비회원이 주문했을 때 결제관리 화면이 다음과 같습니다.
![1](https://cloud.githubusercontent.com/assets/19444926/16105688/a7170d10-33c7-11e6-8da5-bebfa792bfed.jpg)

아이디: 탈퇴한 회원      이름:      닉네임:        두군데 모두 공란입니다.

비회원이 주문한 경우일지라도 주문자의 이름이나 닉네임이라도 보이는게 좋을 듯합니다.

**Comment by bjrambo** [comment]
fixed in
