### ISSUE TITLE
cympusadmin 관리자 화면에서 스킨설정 클릭하여 들어가려니 아래와 같이 에러가 뜨네요.

### ISSUE THREAD

**Issue by linuking** [bjrambo/nurigo#68]
4.  cympusadmin 관리자 화면에서 스킨설정 클릭하여 들어가려니 아래와 같이 에러가 뜨네요.
![cympusadmin1](https://cloud.githubusercontent.com/assets/19444926/16105711/1642d462-33c8-11e6-94b9-6707429c1a68.jpg)
![cympusadmin2](https://cloud.githubusercontent.com/assets/19444926/16105714/1d2273b4-33c8-11e6-8f6e-8bd7acf08805.jpg)

위와 같습니다.
V1.1.1에서 해결된 것은 처리 하시면 될 것 같습니다.

항상 수고 해 주셔서 감사합니다.

**Comment by bjrambo** [comment]
fixed in #59
