### ISSUE TITLE
현재 람보님께서 관리하시는 누리고에 대해 질문이 있습니다.

### ISSUE THREAD

**Issue by merons** [bjrambo/nurigo#69]
KCP PAYPLUS를 통하여 신용카드 또는 계좌이체 결제가 이루어지면, 이메일입력 후 결제요청까지
정상적으로 이루어집니다만. 그 이후 KCP서버로 내용이 전송이 안된다고 합니다.
이에 KCP서버에 문의를 하였더니 전송되는 값이 없으며, 당연히 리턴되는 게 없을거라합니다.
호스팅업체에 문의하였더니 전송방식이 소켓 또는 웹방식 중에 어떤건지 파악하라 하고
호스팅업체에서는 웹방식만 지원한다네요
KCP에 문의하였더니, 이제는 소켓만 지원한답니다.

이 문제가 플러그인 소켓/웹방식 전송문제인 것인지, 누리고 epay 처리방식에 있는것인지 혼동이 옵니다..

**Comment by bjrambo** [comment]
KCP모듈을 사용해보신적 있나요?
KCP모듈이 있지만.. 현재 모듈이 모두 불안정한 상황이라 일부 결제 모듈을 조금 제거하고 이니시스로 할까도 생각중이지만.. 전체적인 파장이 커질것 같아서 고민중이에요.

좀더 보고 살펴볼께요.

**Comment by merons** [comment]
bash2: ./pp_cli: /lib/ld-linux.so.2: bad ELF interpreter: 그런 파일이나 디렉터리가 없습니다
이런 걸로 봐서는 카페24에서 지원을 안해주는거같은데, 이 방식이 웹방식이 아닌 소켓 통신 방식이 맞는거지요?

**Comment by bjrambo** [comment]
제가 서버적인 차원에서는 잘 모르겠고.. 실제적으로 kcp결제가 이루어지는 항목을 좀 다르게 테스트해봐야할 것 같아서요. 일딴 이번 주말에 결제에 관해서 조금 테스트해보고.. 결과물을 말씀드리도록 할게요.

가급적이면, 일반 호스팅기준에서 사용하기에는 이니시스스텐다드로 (여기에도 포함되어있습니다.) 해당 모듈을 이용하여 사용하시는것이 좋습니다.

**Comment by NHbank** [comment]
epay 모듈을 업로드하실 때에는 반드시 바이너리 모드로 진행하셔야 하며, pp_cli 파일의 권한을 755로 설정해 주세요.
