### ISSUE TITLE
formatMoney가 카트에서 작동하지 않는것 같습니다.

### ISSUE THREAD

**Issue by xemania** [bjrambo/nurigo#70]
formatMoney함수가 작동되지 않네요.

{nproductItem::formatMoney($val->sum_discount_amount)} 라고 쓰면,

 "원" 단위가 나오지 않습니다.

p.s / printPrice 함수를 쓰지 않고, formatMoney 함수를 왜 구분해서 카트스킨에 적용했는지 알 수 있을까요?

**Comment by bjrambo** [comment]
ps/항목에 답변을 드리자면.. 제가 원 제작자가 아니라 현제까진 제작에 대한 항목으 ㄹ애이렇게 하신지 정확하게 답변드리기가 어려워요 ㅠㅠ

원제작자의 생각을 알 수 없으니..

다만, 항목을 정상적으로 고치고 개선하는데 집중을 해야하니, 해당항목을 검사하고 고쳐보는데 노력을 해보도록 하겠습니다.

**Comment by bjrambo** [comment]
`nproductItem::formatMoney`는 xemania님이 생각하신것처럼 `1000 원`으로 고치는 용도이기 보단,
`1000` 이라는 숫자를 `1,000`으로 고쳐주는 함수에 가깝습니다.

다음 `원`을 나타내는 단위는 `currency`모듈에서 진행합니다.
