### ISSUE TITLE
number_format 함수도 작동되지 않습니다.

### ISSUE THREAD

**Issue by xemania** [bjrambo/nurigo#73]
number_format 함수도 작동되지 않습니다.

{number_format($val->quantity)} 했을시에 수량(개)이 나타나야 하는데 표시되어지지 않습니다.

**Comment by bjrambo** [comment]
`number_format`은 누리고 함수나 XE함수가 아닌 PHP함수입니다.

다른 문제가 아닌지 다시한번 보시길 바랍니다.
