### ISSUE TITLE
모바일에서 상품페이지 댓글(묻고답하기 등) 쓰면 <br> 태그가 붙는 현상

### ISSUE THREAD

**Issue by treasurej** [bjrambo/nurigo#74]
https://www.cameron.co.kr:47741/qna/102255
여기 신고된 것과 같이
모바일에서 상품페이지 댓글(묻고답하기 등) 쓰면 <br> 태그가 붙는 현상이 있습니다.
누리고 기본 스킨에서도 같은 현상이라서 누리고 관련 문제로 남겼습니다.

XE코어는 1.8.2 입니다.

**Comment by bjrambo** [comment]
fixed in https://github.com/bjrambo/nurigo/commit/44a3f2c417351bb2331bbe8c996dbca3e1c8d3c9
