### ISSUE TITLE
[메일이슈] 할인적용금액이 먹히지 않는 문제점.

### ISSUE THREAD

**Issue by bjrambo** [bjrambo/nurigo#75]
할인에 적용금액을 넣었는데 해당 적용금액이 먹히지 않는 버그 발생했다고함.
확인후, 고쳐야할듯?

**Comment by smg2512** [comment]
할인에 적용금액 넣었는데 먹히지 않는데 버그좀 잡아주세요!!

**Comment by bjrambo** [comment]
fixed in https://github.com/bjrambo/nurigo/commit/bf7609d664efc604ff8b58f7f5f963dcc62a4739 https://github.com/bjrambo/nurigo/commit/60e7faa3e8515d0bb354d66e740ed4745f741669

**Comment by smg2512** [comment]
여쭈어 볼게있습니다.
fixed in  bf7609d   60e7faa  둘다를 수정하라는 것인가요?

**Comment by smg2512** [comment]
여쭈어 볼게 있습니다.
fixed in  bf7609d   60e7faa  둘다를 수정하라는건가요?
아직도 세부 내용에는 적용이 되는데 위젯에서는 동일가격 나와서요..

**Comment by bjrambo** [comment]
@smg2512 두개다요

**Comment by bjrambo** [comment]
@smg2512 그리고사용하시는 스킨에 따라 달라지니 해당 스킨 사용하시는거 있으면 그 스킨의 코드를 변경하시길 바래요.

**Comment by smg2512** [comment]
스킨은 카메룬 스킨 사용하는데 그 쪽 관리자님들도 아실까요?

**Comment by bjrambo** [comment]
@smg2512 제보해주시면됩니다.
