### ISSUE TITLE
currency 모듈 자체가 작동하지 않는것 같습니다.

### ISSUE THREAD

**Issue by xemania** [bjrambo/nurigo#77]
currency 모듈 자체가 작동하지 않는것 같습니다.

달러나, 원화 등의 기호와 원 같은 기호가 함수에 나타나지지 않습니다.

확인부탁드립니다.

**Comment by bjrambo** [comment]
이슈는 정확히 적어주세요.
```
어떤방법으로 어떻게 했으며 원래는 어떻게되길 기대했지만, 이 동작이 되지 않았다.
```
이렇게 구체적인 항목이 있어야 이슈를 해결하는데 도움이 됩니다.

정상적으로 해당 모듈은 작동되는것으로 보여집니다. 자세히 적어서 새로운 이슈로 남겨주시면 감사하겠습니다.
