### ISSUE TITLE
direct_gocart=='Y'" id="dummy_form"> 모바일쪽에서 이런 문자열이 나옵니다.

### ISSUE THREAD

**Issue by imadonis** [bjrambo/nurigo#79]
xetown 에도 올렸지만 여기에도 올립니다.

https://www.xetown.com/qna/347853

누리고 쇼핑몰 트랜드샵 모바일쪽에 이상한 문자열에 대해 질문드립니다.
 
xe 1.8.23  
php 7.0.9
누리고 람보님 패치 1.1.3
카멜론 모바일 트렌드샵 1.0.2
====================
을 사용하고 있습니다.
 
다름이 아니라 모바일에서 볼때 다음과 같은 문자열이 나타납니다.
 
direct_gocart=='Y'" id="dummy_form">
 
구글 개발자도구로 들여다봐도 전혀 문제를 몰라서 ..
 
도움을 청합니다.

**Comment by bjrambo** [comment]
카메론 모바일트렌드샵자체의 코드를 제가 알 수 없어서 도움을 드리기 어렵습니다.

해당 스킨은 스킨 개발자에게 물어보시고, 나오신 원인을 다시한번 알려주시면 좋을것 같아요. (모듈자체의 문제는 아닌것 같군요.)
