### ISSUE TITLE
상품진열 위젯에서 {$val->printDiscountedPrice()}

### ISSUE THREAD

**Issue by treasurej** [bjrambo/nurigo#80]
최신 누리고 버전

상품진열 위젯에서 {$val->printDiscountedPrice()} 여기에 할인이 적용된 값으로 출력되지 않고 있습니다.

상품가가 16만원이고 할인이 4만원이면 12만원이 출력되어야 하는데 상품가인 16만원으로 출력되고 있습니다.

위젯 말고는 나머지 모듈에서는 정상적으로 출력됩니다.

**Comment by bjrambo** [comment]
#75 이슈랑 같네요 :)

위젯뿐만 아니라 스킨에서도 수정이 필요할 것 같습니다.
패치해두겠습니다.

**Comment by bjrambo** [comment]
fixed in https://github.com/bjrambo/nurigo/commit/bf7609d664efc604ff8b58f7f5f963dcc62a4739 https://github.com/bjrambo/nurigo/commit/60e7faa3e8515d0bb354d66e740ed4745f741669
