### ISSUE TITLE
비회원 구매시 회원정보가 탈퇴한 회원으로 보이는 문제

### ISSUE THREAD

**Issue by treasurej** [bjrambo/nurigo#81]
비회원 구매시 회원정보가 탈퇴한 회원으로 보이는 문제
1년 지난 회원이 휴먼계정으로 전환될 때도 탈퇴한 회원으로 보이는 문제가 있음.

**Comment by bjrambo** [comment]
fixed in 0a5179cb697ed5b6450d7f8b50b839951ea7042e
