### ISSUE TITLE
/modules/ncart/m.skins/trendshop/reviewform.html

### ISSUE THREAD

**Issue by blog119** [bjrambo/nurigo#82]
늘 수고 하십니다.
[모바일 장바구니>주문하기>결제 > 신용카드결제] 선택 하면,
Err: '/modules/ncart/m.skins/trendshop/reviewform.html' template files does not exists.

라고 나옵니다. (결제는 진행가능하며, 계좌이체 및 가상계좌도 같은 에러 발생합니다)
그런데, 현재 가장최근 버전인 trendshop_mobile_1.0.2  에는 /modules/ncart/m.skins/trendshop/reviewform.html
파일이 존재하지 않습니다.  
PS. 이경우 카메룬에 문의해야 하는건가요?

**Comment by bjrambo** [comment]
최신버전의 경우에도 동일한 문제가 발생하는지 확인해보시고.. 저도 나중에 시간되면 확인해보도록 하겠습니다.

**Comment by bjrambo** [comment]
아하 최신버전에서 해당 기능을 추가한 부분이기때문에 카메론샵에 물어보시면 될것 같네요 :)
