### ISSUE TITLE
최근 배송지에 같은 배송지가 계속 쌓이는 문제

### ISSUE THREAD

**Issue by treasurej** [bjrambo/nurigo#89]
최근 배송지에 같은 배송지가 계속 쌓이는 문제
![2016-09-08](https://cloud.githubusercontent.com/assets/4101147/18317872/6b97f342-755a-11e6-81ce-0b6edbfd5684.png)

배송지 정보가 같을 때는 추가되는 것이 아니라 대체 되었으면 좋겠습니다.
같은 과거 배송지가 삭제되고 같은 최근 배송지가 상위로 올라오는 형식이요~^^

**Comment by bjrambo** [comment]
오잉..? 어떻게 해서 이런동작을 하게됬는지 알 수 있을까요?

**Comment by treasurej** [comment]
결제화면에서 기본배송지와 최근배송지 선택 버튼이 있어요~
최근배송지 누르면 최근에 주문했던 배송지 목록이 떠요.
주문은 안하더라도, 결제하기 하면 최근 배송지에 추가되니 쉽게 테스트해 보실 수 있어요^^

**Comment by bjrambo** [comment]
확인해보니, 압축한 데이터를 이용하여 주소록에서 가져오는 방법을 쓰고 잇었습니다.

(주소데이터가 모두 압축..)

그래서 각각 다른 데이터들으로 저장됩니다.. (상품명, 주소이름, 번지수, 이름 등등을 모두 압축해서..)
그래서 주소만 딱 검색할 수 있는 상황이 없고, 그나마 가져오는 데이터로는 시리얼 넘버인데 이건 기존에 이 주소가 맞는지 확인하는 용도가 불가능할 것 같습니다.

그렇다고 이를 풀어서 모든 데이터를 대조하게 되면 성능상 안그래도 느린 항목이 좀 더 느린 항목이 될 우려도 높네요.

이건 기능에 개선여지가 조금 더 확인해봐야할 사항인것 같습니다. (마이그레이션 필요할 듯 합니다.)
