### ISSUE TITLE
상품관리 추가등록폼 다중선택(checkbox) 내용 저장시 초기화되는 현상

### ISSUE THREAD

**Issue by treasurej** [bjrambo/nurigo#92]
상품관리 추가등록폼 다중선택(checkbox) 내용 저장시 초기화되는 현상
1. 추가등록폼을 등록합니다.
   ![2016-09-08 1](https://cloud.githubusercontent.com/assets/4101147/18338567/db2408de-75d4-11e6-9d24-3a49be68b665.png)
2. 다중선택(checkbox)로 선택하면 내용입력란이 나옵니다. 이곳에 입력하고 저장하면
   ![2016-09-08 2](https://cloud.githubusercontent.com/assets/4101147/18338571/ded52288-75d4-11e6-9360-df76bf534f16.png)
3. 저장되지 않고 비어서 저장이 되는 현상
   ![2016-09-08 3](https://cloud.githubusercontent.com/assets/4101147/18338574/e1988e1a-75d4-11e6-9bc3-4669457e523a.png)

서버정보
app : Apache/2.4.6 (Win64) PHP/5.5.3
xe_version : 1.8.24
php : 5.5.3
db_type : mysqli

**Comment by bjrambo** [comment]
해당 문제가 재현되지 않습니다.
