### ISSUE TITLE
통합검색시 게시물 검색 목록에 출력되지 않습니다. (게시물탭 클릭시 보임)

### ISSUE THREAD

**Issue by Seonsik** [bjrambo/nurigo#93]
![1](https://cloud.githubusercontent.com/assets/22054665/18610711/2f1e1386-7d5e-11e6-8a00-0d68a509acad.jpg)
![2](https://cloud.githubusercontent.com/assets/22054665/18610712/2f1e47d4-7d5e-11e6-8de6-ab53272aedc7.jpg)
![3](https://cloud.githubusercontent.com/assets/22054665/18610715/2f28d7e4-7d5e-11e6-94c7-993eb65479cd.jpg)
게시물 에대한 검색은 통합검색 탭에 출력이 안됩니다만
아래 첨부이미지처럼  상품은 바로 보여집니다.
![4](https://cloud.githubusercontent.com/assets/22054665/18610714/2f27f61c-7d5e-11e6-85f8-8843cbc14b88.jpg)

혹시나몰라 상품통합검색확장 모듈 삭제하고 테스트해보니 정상적으로 보여집니다.
![5](https://cloud.githubusercontent.com/assets/22054665/18610713/2f255448-7d5e-11e6-86d7-19517537aaa8.jpg)

테스트중 발견한점이 있는데
상품등록(상품글작성)된 시점기준으로 이전 게시글들은 통합검색에 정상출력됩니다.
상품등록된 시점 이후의 게시글들은 통합검색시 위 이슈처럼 "게시물" 탭을 클릭해야지만
볼수 있습니다.

유추해본결과 상품등록된 기준으로 일반 게시물 글들이 통합검색에 보이거나 안보이는것 같습니다.

**Comment by bjrambo** [comment]
fixed in 5c8d0d47ed6f5c8c084205590273cdf7bdecbc61
