### ISSUE TITLE
관리자 스킨 기능

### ISSUE THREAD

**Issue by eondcom** [bjrambo/nurigo#97]
cympus/skins/default
폴더명을 추가로 생성해서 하나를 새로 만들었는데,
아직 관리자 스킨 기능이 적용은 안되는 것 같네요..

/modules/cympusadmin/cympusadmin.model.php
26번째줄에 폴더명을 바꿔주면 되던데, 임시로 우선 이렇게 사용해볼게요..

**Comment by bjrambo** [comment]
cympus/skins/원하는파일명 이렇게 넣으셧나요?

**Comment by eondcom** [comment]
네 그렇게 넣었습니다.

**Comment by eondcom** [comment]
관리자 설정은 되는데, 적용은 안되던??

**Comment by bjrambo** [comment]
확인해볼게요

**Comment by bjrambo** [comment]
fixed in https://github.com/bjrambo/nurigo/commit/0b8b2564796811bd8d60dbab0e889bfcf5cfff74
